// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.1
// source: libatbus_protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ATBUS_PROTOCOL_CONST int32

const (
	ATBUS_PROTOCOL_CONST_ATBUS_PROTOCOL_CONST_UNKNOWN   ATBUS_PROTOCOL_CONST = 0
	ATBUS_PROTOCOL_CONST_ATBUS_PROTOCOL_VERSION         ATBUS_PROTOCOL_CONST = 3
	ATBUS_PROTOCOL_CONST_ATBUS_PROTOCOL_MINIMAL_VERSION ATBUS_PROTOCOL_CONST = 3 // minimal protocol version supported
)

// Enum value maps for ATBUS_PROTOCOL_CONST.
var (
	ATBUS_PROTOCOL_CONST_name = map[int32]string{
		0: "ATBUS_PROTOCOL_CONST_UNKNOWN",
		3: "ATBUS_PROTOCOL_VERSION",
		// Duplicate value: 3: "ATBUS_PROTOCOL_MINIMAL_VERSION",
	}
	ATBUS_PROTOCOL_CONST_value = map[string]int32{
		"ATBUS_PROTOCOL_CONST_UNKNOWN":   0,
		"ATBUS_PROTOCOL_VERSION":         3,
		"ATBUS_PROTOCOL_MINIMAL_VERSION": 3,
	}
)

func (x ATBUS_PROTOCOL_CONST) Enum() *ATBUS_PROTOCOL_CONST {
	p := new(ATBUS_PROTOCOL_CONST)
	*p = x
	return p
}

func (x ATBUS_PROTOCOL_CONST) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_PROTOCOL_CONST) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[0].Descriptor()
}

func (ATBUS_PROTOCOL_CONST) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[0]
}

func (x ATBUS_PROTOCOL_CONST) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_PROTOCOL_CONST.Descriptor instead.
func (ATBUS_PROTOCOL_CONST) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{0}
}

type ATBUS_FORWARD_DATA_FLAG_TYPE int32

const (
	ATBUS_FORWARD_DATA_FLAG_TYPE_FORWARD_DATA_FLAG_NONE ATBUS_FORWARD_DATA_FLAG_TYPE = 0
	// all flags must be power of 2
	ATBUS_FORWARD_DATA_FLAG_TYPE_FORWARD_DATA_FLAG_REQUIRE_RSP ATBUS_FORWARD_DATA_FLAG_TYPE = 1
)

// Enum value maps for ATBUS_FORWARD_DATA_FLAG_TYPE.
var (
	ATBUS_FORWARD_DATA_FLAG_TYPE_name = map[int32]string{
		0: "FORWARD_DATA_FLAG_NONE",
		1: "FORWARD_DATA_FLAG_REQUIRE_RSP",
	}
	ATBUS_FORWARD_DATA_FLAG_TYPE_value = map[string]int32{
		"FORWARD_DATA_FLAG_NONE":        0,
		"FORWARD_DATA_FLAG_REQUIRE_RSP": 1,
	}
)

func (x ATBUS_FORWARD_DATA_FLAG_TYPE) Enum() *ATBUS_FORWARD_DATA_FLAG_TYPE {
	p := new(ATBUS_FORWARD_DATA_FLAG_TYPE)
	*p = x
	return p
}

func (x ATBUS_FORWARD_DATA_FLAG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_FORWARD_DATA_FLAG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[1].Descriptor()
}

func (ATBUS_FORWARD_DATA_FLAG_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[1]
}

func (x ATBUS_FORWARD_DATA_FLAG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_FORWARD_DATA_FLAG_TYPE.Descriptor instead.
func (ATBUS_FORWARD_DATA_FLAG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{1}
}

type ATBUS_ACCESS_DATA_ALGORITHM_TYPE int32

const (
	ATBUS_ACCESS_DATA_ALGORITHM_TYPE_ATBUS_ACCESS_DATA_ALGORITHM_HMAC_SHA256 ATBUS_ACCESS_DATA_ALGORITHM_TYPE = 0
)

// Enum value maps for ATBUS_ACCESS_DATA_ALGORITHM_TYPE.
var (
	ATBUS_ACCESS_DATA_ALGORITHM_TYPE_name = map[int32]string{
		0: "ATBUS_ACCESS_DATA_ALGORITHM_HMAC_SHA256",
	}
	ATBUS_ACCESS_DATA_ALGORITHM_TYPE_value = map[string]int32{
		"ATBUS_ACCESS_DATA_ALGORITHM_HMAC_SHA256": 0,
	}
)

func (x ATBUS_ACCESS_DATA_ALGORITHM_TYPE) Enum() *ATBUS_ACCESS_DATA_ALGORITHM_TYPE {
	p := new(ATBUS_ACCESS_DATA_ALGORITHM_TYPE)
	*p = x
	return p
}

func (x ATBUS_ACCESS_DATA_ALGORITHM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_ACCESS_DATA_ALGORITHM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[2].Descriptor()
}

func (ATBUS_ACCESS_DATA_ALGORITHM_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[2]
}

func (x ATBUS_ACCESS_DATA_ALGORITHM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_ACCESS_DATA_ALGORITHM_TYPE.Descriptor instead.
func (ATBUS_ACCESS_DATA_ALGORITHM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{2}
}

type ATBUS_CRYPTO_KDF_TYPE int32

const (
	ATBUS_CRYPTO_KDF_TYPE_ATBUS_CRYPTO_KDF_HKDF_SHA256 ATBUS_CRYPTO_KDF_TYPE = 0
)

// Enum value maps for ATBUS_CRYPTO_KDF_TYPE.
var (
	ATBUS_CRYPTO_KDF_TYPE_name = map[int32]string{
		0: "ATBUS_CRYPTO_KDF_HKDF_SHA256",
	}
	ATBUS_CRYPTO_KDF_TYPE_value = map[string]int32{
		"ATBUS_CRYPTO_KDF_HKDF_SHA256": 0,
	}
)

func (x ATBUS_CRYPTO_KDF_TYPE) Enum() *ATBUS_CRYPTO_KDF_TYPE {
	p := new(ATBUS_CRYPTO_KDF_TYPE)
	*p = x
	return p
}

func (x ATBUS_CRYPTO_KDF_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_CRYPTO_KDF_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[3].Descriptor()
}

func (ATBUS_CRYPTO_KDF_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[3]
}

func (x ATBUS_CRYPTO_KDF_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_CRYPTO_KDF_TYPE.Descriptor instead.
func (ATBUS_CRYPTO_KDF_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{3}
}

type ATBUS_CRYPTO_ALGORITHM_TYPE int32

const (
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_NONE                    ATBUS_CRYPTO_ALGORITHM_TYPE = 0
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_XXTEA                   ATBUS_CRYPTO_ALGORITHM_TYPE = 1
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_128_CBC             ATBUS_CRYPTO_ALGORITHM_TYPE = 11 // PKCS#7
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_192_CBC             ATBUS_CRYPTO_ALGORITHM_TYPE = 12 // PKCS#7
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_256_CBC             ATBUS_CRYPTO_ALGORITHM_TYPE = 13 // PKCS#7
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_128_GCM             ATBUS_CRYPTO_ALGORITHM_TYPE = 14 // AEAD
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_192_GCM             ATBUS_CRYPTO_ALGORITHM_TYPE = 15 // AEAD
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_AES_256_GCM             ATBUS_CRYPTO_ALGORITHM_TYPE = 16 // AEAD
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_CHACHA20                ATBUS_CRYPTO_ALGORITHM_TYPE = 31
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_CHACHA20_POLY1305_IETF  ATBUS_CRYPTO_ALGORITHM_TYPE = 32 // AEAD
	ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_XCHACHA20_POLY1305_IETF ATBUS_CRYPTO_ALGORITHM_TYPE = 33 // AEAD
)

// Enum value maps for ATBUS_CRYPTO_ALGORITHM_TYPE.
var (
	ATBUS_CRYPTO_ALGORITHM_TYPE_name = map[int32]string{
		0:  "ATBUS_CRYPTO_ALGORITHM_NONE",
		1:  "ATBUS_CRYPTO_ALGORITHM_XXTEA",
		11: "ATBUS_CRYPTO_ALGORITHM_AES_128_CBC",
		12: "ATBUS_CRYPTO_ALGORITHM_AES_192_CBC",
		13: "ATBUS_CRYPTO_ALGORITHM_AES_256_CBC",
		14: "ATBUS_CRYPTO_ALGORITHM_AES_128_GCM",
		15: "ATBUS_CRYPTO_ALGORITHM_AES_192_GCM",
		16: "ATBUS_CRYPTO_ALGORITHM_AES_256_GCM",
		31: "ATBUS_CRYPTO_ALGORITHM_CHACHA20",
		32: "ATBUS_CRYPTO_ALGORITHM_CHACHA20_POLY1305_IETF",
		33: "ATBUS_CRYPTO_ALGORITHM_XCHACHA20_POLY1305_IETF",
	}
	ATBUS_CRYPTO_ALGORITHM_TYPE_value = map[string]int32{
		"ATBUS_CRYPTO_ALGORITHM_NONE":                    0,
		"ATBUS_CRYPTO_ALGORITHM_XXTEA":                   1,
		"ATBUS_CRYPTO_ALGORITHM_AES_128_CBC":             11,
		"ATBUS_CRYPTO_ALGORITHM_AES_192_CBC":             12,
		"ATBUS_CRYPTO_ALGORITHM_AES_256_CBC":             13,
		"ATBUS_CRYPTO_ALGORITHM_AES_128_GCM":             14,
		"ATBUS_CRYPTO_ALGORITHM_AES_192_GCM":             15,
		"ATBUS_CRYPTO_ALGORITHM_AES_256_GCM":             16,
		"ATBUS_CRYPTO_ALGORITHM_CHACHA20":                31,
		"ATBUS_CRYPTO_ALGORITHM_CHACHA20_POLY1305_IETF":  32,
		"ATBUS_CRYPTO_ALGORITHM_XCHACHA20_POLY1305_IETF": 33,
	}
)

func (x ATBUS_CRYPTO_ALGORITHM_TYPE) Enum() *ATBUS_CRYPTO_ALGORITHM_TYPE {
	p := new(ATBUS_CRYPTO_ALGORITHM_TYPE)
	*p = x
	return p
}

func (x ATBUS_CRYPTO_ALGORITHM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_CRYPTO_ALGORITHM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[4].Descriptor()
}

func (ATBUS_CRYPTO_ALGORITHM_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[4]
}

func (x ATBUS_CRYPTO_ALGORITHM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_CRYPTO_ALGORITHM_TYPE.Descriptor instead.
func (ATBUS_CRYPTO_ALGORITHM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{4}
}

type ATBUS_CRYPTO_KEY_EXCHANGE_TYPE int32

const (
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_NONE ATBUS_CRYPTO_KEY_EXCHANGE_TYPE = 0
	// golang 标准库只支持ECDH
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_X25519    ATBUS_CRYPTO_KEY_EXCHANGE_TYPE = 1 // x25519(TLS 1.3推荐)
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_SECP256R1 ATBUS_CRYPTO_KEY_EXCHANGE_TYPE = 2 // secp256r1, p-256
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_SECP384R1 ATBUS_CRYPTO_KEY_EXCHANGE_TYPE = 3 // secp384r1, p-384
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_SECP521R1 ATBUS_CRYPTO_KEY_EXCHANGE_TYPE = 4 // secp521r1, p-521
)

// Enum value maps for ATBUS_CRYPTO_KEY_EXCHANGE_TYPE.
var (
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_name = map[int32]string{
		0: "ATBUS_CRYPTO_KEY_EXCHANGE_NONE",
		1: "ATBUS_CRYPTO_KEY_EXCHANGE_X25519",
		2: "ATBUS_CRYPTO_KEY_EXCHANGE_SECP256R1",
		3: "ATBUS_CRYPTO_KEY_EXCHANGE_SECP384R1",
		4: "ATBUS_CRYPTO_KEY_EXCHANGE_SECP521R1",
	}
	ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_value = map[string]int32{
		"ATBUS_CRYPTO_KEY_EXCHANGE_NONE":      0,
		"ATBUS_CRYPTO_KEY_EXCHANGE_X25519":    1,
		"ATBUS_CRYPTO_KEY_EXCHANGE_SECP256R1": 2,
		"ATBUS_CRYPTO_KEY_EXCHANGE_SECP384R1": 3,
		"ATBUS_CRYPTO_KEY_EXCHANGE_SECP521R1": 4,
	}
)

func (x ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) Enum() *ATBUS_CRYPTO_KEY_EXCHANGE_TYPE {
	p := new(ATBUS_CRYPTO_KEY_EXCHANGE_TYPE)
	*p = x
	return p
}

func (x ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[5].Descriptor()
}

func (ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[5]
}

func (x ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_CRYPTO_KEY_EXCHANGE_TYPE.Descriptor instead.
func (ATBUS_CRYPTO_KEY_EXCHANGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{5}
}

type ATBUS_COMPRESSION_ALGORITHM_TYPE int32

const (
	ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_NONE   ATBUS_COMPRESSION_ALGORITHM_TYPE = 0
	ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_ZSTD   ATBUS_COMPRESSION_ALGORITHM_TYPE = 100
	ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_LZ4    ATBUS_COMPRESSION_ALGORITHM_TYPE = 200
	ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_SNAPPY ATBUS_COMPRESSION_ALGORITHM_TYPE = 300
	ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_ZLIB   ATBUS_COMPRESSION_ALGORITHM_TYPE = 400
)

// Enum value maps for ATBUS_COMPRESSION_ALGORITHM_TYPE.
var (
	ATBUS_COMPRESSION_ALGORITHM_TYPE_name = map[int32]string{
		0:   "ATBUS_COMPRESSION_ALGORITHM_NONE",
		100: "ATBUS_COMPRESSION_ALGORITHM_ZSTD",
		200: "ATBUS_COMPRESSION_ALGORITHM_LZ4",
		300: "ATBUS_COMPRESSION_ALGORITHM_SNAPPY",
		400: "ATBUS_COMPRESSION_ALGORITHM_ZLIB",
	}
	ATBUS_COMPRESSION_ALGORITHM_TYPE_value = map[string]int32{
		"ATBUS_COMPRESSION_ALGORITHM_NONE":   0,
		"ATBUS_COMPRESSION_ALGORITHM_ZSTD":   100,
		"ATBUS_COMPRESSION_ALGORITHM_LZ4":    200,
		"ATBUS_COMPRESSION_ALGORITHM_SNAPPY": 300,
		"ATBUS_COMPRESSION_ALGORITHM_ZLIB":   400,
	}
)

func (x ATBUS_COMPRESSION_ALGORITHM_TYPE) Enum() *ATBUS_COMPRESSION_ALGORITHM_TYPE {
	p := new(ATBUS_COMPRESSION_ALGORITHM_TYPE)
	*p = x
	return p
}

func (x ATBUS_COMPRESSION_ALGORITHM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_COMPRESSION_ALGORITHM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[6].Descriptor()
}

func (ATBUS_COMPRESSION_ALGORITHM_TYPE) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[6]
}

func (x ATBUS_COMPRESSION_ALGORITHM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_COMPRESSION_ALGORITHM_TYPE.Descriptor instead.
func (ATBUS_COMPRESSION_ALGORITHM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{6}
}

// 统一压缩等级定义，用于抽象不同压缩算法的压缩强度。
// 枚举值表达语义等级，具体算法参数由实现层映射。
type ATBUS_COMPRESSION_LEVEL int32

const (
	// 默认值：使用各压缩算法的默认推荐配置
	//
	// 典型映射：
	//
	//	zstd   : level 3
	//	lz4    : fast 默认
	//	snappy : 默认配置
	//	zlib   : level 6
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_DEFAULT ATBUS_COMPRESSION_LEVEL = 0
	// 存储优先：最低 CPU 开销，允许不压缩直接存储
	//
	// 典型映射：
	//
	//	zstd   : level 1（或 0）
	//	lz4    : fast(1)
	//	snappy : 默认配置
	//	zlib   : level 1
	//	none   : 不压缩
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_STORAGE ATBUS_COMPRESSION_LEVEL = 100
	// 极速压缩，强调最低 CPU 与延迟
	//
	// 典型映射：
	//
	//	zstd   : level -1
	//	lz4    : fast(1)
	//	snappy : 默认配置
	//	zlib   : level 1
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_FAST ATBUS_COMPRESSION_LEVEL = 200
	// 低 CPU 开销压缩，在性能与压缩率之间轻度折中
	//
	// 典型映射：
	//
	//	zstd   : level 1
	//	lz4    : fast(3)
	//	zlib   : level 3
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_LOW_CPU ATBUS_COMPRESSION_LEVEL = 300
	// 均衡压缩，作为系统推荐的通用等级
	//
	// 典型映射：
	//
	//	zstd   : level 3
	//	lz4    : fast(6)
	//	zlib   : level 6
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_BALANCED ATBUS_COMPRESSION_LEVEL = 400
	// 高压缩率，存储优先，允许较高 CPU 成本
	//
	// 典型映射：
	//
	//	zstd   : level 6
	//	lz4    : hc(9)
	//	zlib   : level 9
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_HIGH_RATIO ATBUS_COMPRESSION_LEVEL = 500
	// 极限压缩，仅适用于冷数据或离线场景
	//
	// 典型映射：
	//
	//	zstd   : level 9 ~ 15
	ATBUS_COMPRESSION_LEVEL_ATBUS_COMPRESSION_LEVEL_MAX_RATIO ATBUS_COMPRESSION_LEVEL = 600
)

// Enum value maps for ATBUS_COMPRESSION_LEVEL.
var (
	ATBUS_COMPRESSION_LEVEL_name = map[int32]string{
		0:   "ATBUS_COMPRESSION_LEVEL_DEFAULT",
		100: "ATBUS_COMPRESSION_LEVEL_STORAGE",
		200: "ATBUS_COMPRESSION_LEVEL_FAST",
		300: "ATBUS_COMPRESSION_LEVEL_LOW_CPU",
		400: "ATBUS_COMPRESSION_LEVEL_BALANCED",
		500: "ATBUS_COMPRESSION_LEVEL_HIGH_RATIO",
		600: "ATBUS_COMPRESSION_LEVEL_MAX_RATIO",
	}
	ATBUS_COMPRESSION_LEVEL_value = map[string]int32{
		"ATBUS_COMPRESSION_LEVEL_DEFAULT":    0,
		"ATBUS_COMPRESSION_LEVEL_STORAGE":    100,
		"ATBUS_COMPRESSION_LEVEL_FAST":       200,
		"ATBUS_COMPRESSION_LEVEL_LOW_CPU":    300,
		"ATBUS_COMPRESSION_LEVEL_BALANCED":   400,
		"ATBUS_COMPRESSION_LEVEL_HIGH_RATIO": 500,
		"ATBUS_COMPRESSION_LEVEL_MAX_RATIO":  600,
	}
)

func (x ATBUS_COMPRESSION_LEVEL) Enum() *ATBUS_COMPRESSION_LEVEL {
	p := new(ATBUS_COMPRESSION_LEVEL)
	*p = x
	return p
}

func (x ATBUS_COMPRESSION_LEVEL) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ATBUS_COMPRESSION_LEVEL) Descriptor() protoreflect.EnumDescriptor {
	return file_libatbus_protocol_proto_enumTypes[7].Descriptor()
}

func (ATBUS_COMPRESSION_LEVEL) Type() protoreflect.EnumType {
	return &file_libatbus_protocol_proto_enumTypes[7]
}

func (x ATBUS_COMPRESSION_LEVEL) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ATBUS_COMPRESSION_LEVEL.Descriptor instead.
func (ATBUS_COMPRESSION_LEVEL) EnumDescriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{7}
}

type CryptoHandshakeData struct {
	state      protoimpl.MessageState         `protogen:"open.v1"`
	Sequence   uint64                         `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // used to prevent duplication
	Type       ATBUS_CRYPTO_KEY_EXCHANGE_TYPE `protobuf:"varint,2,opt,name=type,proto3,enum=atframework.atbus.protocol.ATBUS_CRYPTO_KEY_EXCHANGE_TYPE" json:"type,omitempty"`
	KdfType    []ATBUS_CRYPTO_KDF_TYPE        `protobuf:"varint,3,rep,packed,name=kdf_type,json=kdfType,proto3,enum=atframework.atbus.protocol.ATBUS_CRYPTO_KDF_TYPE" json:"kdf_type,omitempty"`
	Algorithms []ATBUS_CRYPTO_ALGORITHM_TYPE  `protobuf:"varint,4,rep,packed,name=algorithms,proto3,enum=atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPE" json:"algorithms,omitempty"` // available cryptographic algorithms
	// golang 标准库接口不支持生成 TLS 1.2 ECDHE ServerKeyExchange 结构
	// 为了兼容性我们采用 ATBUS_CRYPTO_KEY_EXCHANGE_TYPE 字段标识密钥交换类型，两边配置一致
	// 要求跨语言、跨加密库时需要保证算法都受到支持。
	// 密钥生成算法:
	//   - ATBUS_CRYPTO_KDF_HKDF_SHA256 -> HKDF(sha256(), shared_secret, nil, nil)
	//   - 内容: [KEY][IV]
	PublicKey []byte `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 初始iv size for crypto, must be same as the selected algorithm requirement
	IvSize uint32 `protobuf:"varint,11,opt,name=iv_size,json=ivSize,proto3" json:"iv_size,omitempty"`
	// tag length for AEAD
	TagSize       uint32 `protobuf:"varint,21,opt,name=tag_size,json=tagSize,proto3" json:"tag_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoHandshakeData) Reset() {
	*x = CryptoHandshakeData{}
	mi := &file_libatbus_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoHandshakeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoHandshakeData) ProtoMessage() {}

func (x *CryptoHandshakeData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoHandshakeData.ProtoReflect.Descriptor instead.
func (*CryptoHandshakeData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoHandshakeData) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CryptoHandshakeData) GetType() ATBUS_CRYPTO_KEY_EXCHANGE_TYPE {
	if x != nil {
		return x.Type
	}
	return ATBUS_CRYPTO_KEY_EXCHANGE_TYPE_ATBUS_CRYPTO_KEY_EXCHANGE_NONE
}

func (x *CryptoHandshakeData) GetKdfType() []ATBUS_CRYPTO_KDF_TYPE {
	if x != nil {
		return x.KdfType
	}
	return nil
}

func (x *CryptoHandshakeData) GetAlgorithms() []ATBUS_CRYPTO_ALGORITHM_TYPE {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *CryptoHandshakeData) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *CryptoHandshakeData) GetIvSize() uint32 {
	if x != nil {
		return x.IvSize
	}
	return 0
}

func (x *CryptoHandshakeData) GetTagSize() uint32 {
	if x != nil {
		return x.TagSize
	}
	return 0
}

type CustomCommandArgv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arg           []byte                 `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCommandArgv) Reset() {
	*x = CustomCommandArgv{}
	mi := &file_libatbus_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCommandArgv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCommandArgv) ProtoMessage() {}

func (x *CustomCommandArgv) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCommandArgv.ProtoReflect.Descriptor instead.
func (*CustomCommandArgv) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *CustomCommandArgv) GetArg() []byte {
	if x != nil {
		return x.Arg
	}
	return nil
}

type CustomCommandData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Commands      []*CustomCommandArgv   `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	AccessKey     *AccessData            `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCommandData) Reset() {
	*x = CustomCommandData{}
	mi := &file_libatbus_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCommandData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCommandData) ProtoMessage() {}

func (x *CustomCommandData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCommandData.ProtoReflect.Descriptor instead.
func (*CustomCommandData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *CustomCommandData) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *CustomCommandData) GetCommands() []*CustomCommandArgv {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *CustomCommandData) GetAccessKey() *AccessData {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

type ForwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Router        []uint64               `protobuf:"varint,3,rep,packed,name=router,proto3" json:"router,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardData) Reset() {
	*x = ForwardData{}
	mi := &file_libatbus_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardData) ProtoMessage() {}

func (x *ForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardData.ProtoReflect.Descriptor instead.
func (*ForwardData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardData) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ForwardData) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ForwardData) GetRouter() []uint64 {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *ForwardData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ForwardData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type AccessData struct {
	state     protoimpl.MessageState           `protogen:"open.v1"`
	Algorithm ATBUS_ACCESS_DATA_ALGORITHM_TYPE `protobuf:"varint,1,opt,name=algorithm,proto3,enum=atframework.atbus.protocol.ATBUS_ACCESS_DATA_ALGORITHM_TYPE" json:"algorithm,omitempty"`
	Timestamp int64                            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix timestamp
	// 128bits nonce is enough
	// - TLS 1.3: 96 bits
	// - IPSec:   64 bits
	// - JWT:     128 bits
	// - UUID v4: 128 bits
	Nonce1 uint64 `protobuf:"varint,3,opt,name=nonce1,proto3" json:"nonce1,omitempty"` // random
	Nonce2 uint64 `protobuf:"varint,4,opt,name=nonce2,proto3" json:"nonce2,omitempty"` // random
	// access_token="<timestamp>:<nonce1>-<nonce2>:<register_data.bus_id>:{register_data.crypto_handshake.type}:{hex(sha256_lower_case(register_data.crypto_handshake.public_key))}"
	// access_token="<timestamp>:<nonce1>-<nonce2>:<register_data.bus_id>" (without encryption)
	// access_token="<timestamp>:<nonce1>-<nonce2>:<custom_command_data.from>:{hex(sha256_lower_case(custom_command_data.commands.arg))}"
	// abs(timestamp-current time)<=300
	// access_token must be lower than 32KB
	Signature     [][]byte `protobuf:"bytes,9,rep,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessData) Reset() {
	*x = AccessData{}
	mi := &file_libatbus_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessData) ProtoMessage() {}

func (x *AccessData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessData.ProtoReflect.Descriptor instead.
func (*AccessData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *AccessData) GetAlgorithm() ATBUS_ACCESS_DATA_ALGORITHM_TYPE {
	if x != nil {
		return x.Algorithm
	}
	return ATBUS_ACCESS_DATA_ALGORITHM_TYPE_ATBUS_ACCESS_DATA_ALGORITHM_HMAC_SHA256
}

func (x *AccessData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AccessData) GetNonce1() uint64 {
	if x != nil {
		return x.Nonce1
	}
	return 0
}

func (x *AccessData) GetNonce2() uint64 {
	if x != nil {
		return x.Nonce2
	}
	return 0
}

func (x *AccessData) GetSignature() [][]byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ChannelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelData) Reset() {
	*x = ChannelData{}
	mi := &file_libatbus_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelData) ProtoMessage() {}

func (x *ChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelData.ProtoReflect.Descriptor instead.
func (*ChannelData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PingData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimePoint       int64                  `protobuf:"varint,1,opt,name=time_point,json=timePoint,proto3" json:"time_point,omitempty"`
	CryptoHandshake *CryptoHandshakeData   `protobuf:"bytes,2,opt,name=crypto_handshake,json=cryptoHandshake,proto3" json:"crypto_handshake,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingData) Reset() {
	*x = PingData{}
	mi := &file_libatbus_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingData) ProtoMessage() {}

func (x *PingData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingData.ProtoReflect.Descriptor instead.
func (*PingData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PingData) GetTimePoint() int64 {
	if x != nil {
		return x.TimePoint
	}
	return 0
}

func (x *PingData) GetCryptoHandshake() *CryptoHandshakeData {
	if x != nil {
		return x.CryptoHandshake
	}
	return nil
}

type RegisterData struct {
	state                         protoimpl.MessageState             `protogen:"open.v1"`
	BusId                         uint64                             `protobuf:"varint,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	Pid                           int32                              `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Hostname                      string                             `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Channels                      []*ChannelData                     `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	SupportedChannelSchema        []string                           `protobuf:"bytes,5,rep,name=supported_channel_schema,json=supportedChannelSchema,proto3" json:"supported_channel_schema,omitempty"`
	SupportedCompressionAlgorithm []ATBUS_COMPRESSION_ALGORITHM_TYPE `protobuf:"varint,6,rep,packed,name=supported_compression_algorithm,json=supportedCompressionAlgorithm,proto3,enum=atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPE" json:"supported_compression_algorithm,omitempty"`
	Flags                         uint32                             `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	AccessKey                     *AccessData                        `protobuf:"bytes,8,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	HashCode                      string                             `protobuf:"bytes,10,opt,name=hash_code,json=hashCode,proto3" json:"hash_code,omitempty"`
	CryptoHandshake               *CryptoHandshakeData               `protobuf:"bytes,11,opt,name=crypto_handshake,json=cryptoHandshake,proto3" json:"crypto_handshake,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_libatbus_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterData) GetBusId() uint64 {
	if x != nil {
		return x.BusId
	}
	return 0
}

func (x *RegisterData) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RegisterData) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterData) GetChannels() []*ChannelData {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *RegisterData) GetSupportedChannelSchema() []string {
	if x != nil {
		return x.SupportedChannelSchema
	}
	return nil
}

func (x *RegisterData) GetSupportedCompressionAlgorithm() []ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if x != nil {
		return x.SupportedCompressionAlgorithm
	}
	return nil
}

func (x *RegisterData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RegisterData) GetAccessKey() *AccessData {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

func (x *RegisterData) GetHashCode() string {
	if x != nil {
		return x.HashCode
	}
	return ""
}

func (x *RegisterData) GetCryptoHandshake() *CryptoHandshakeData {
	if x != nil {
		return x.CryptoHandshake
	}
	return nil
}

type HandshakeConfirmData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // used to prevent duplication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeConfirmData) Reset() {
	*x = HandshakeConfirmData{}
	mi := &file_libatbus_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeConfirmData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeConfirmData) ProtoMessage() {}

func (x *HandshakeConfirmData) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeConfirmData.ProtoReflect.Descriptor instead.
func (*HandshakeConfirmData) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeConfirmData) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type MessageHeadCrypto struct {
	state     protoimpl.MessageState      `protogen:"open.v1"`
	Algorithm ATBUS_CRYPTO_ALGORITHM_TYPE `protobuf:"varint,1,opt,name=algorithm,proto3,enum=atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPE" json:"algorithm,omitempty"`
	// IV/nonce for crypto, must be unique for each encryption
	// If not set, just used the default rotation/nonce rule of the algorithm
	Iv []byte `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	// AAD for AEAD
	Aad           []byte `protobuf:"bytes,11,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeadCrypto) Reset() {
	*x = MessageHeadCrypto{}
	mi := &file_libatbus_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeadCrypto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeadCrypto) ProtoMessage() {}

func (x *MessageHeadCrypto) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeadCrypto.ProtoReflect.Descriptor instead.
func (*MessageHeadCrypto) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *MessageHeadCrypto) GetAlgorithm() ATBUS_CRYPTO_ALGORITHM_TYPE {
	if x != nil {
		return x.Algorithm
	}
	return ATBUS_CRYPTO_ALGORITHM_TYPE_ATBUS_CRYPTO_ALGORITHM_NONE
}

func (x *MessageHeadCrypto) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *MessageHeadCrypto) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type MessageHeadCompression struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Type          ATBUS_COMPRESSION_ALGORITHM_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPE" json:"type,omitempty"`
	OriginalSize  uint64                           `protobuf:"varint,2,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHeadCompression) Reset() {
	*x = MessageHeadCompression{}
	mi := &file_libatbus_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeadCompression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeadCompression) ProtoMessage() {}

func (x *MessageHeadCompression) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeadCompression.ProtoReflect.Descriptor instead.
func (*MessageHeadCompression) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *MessageHeadCompression) GetType() ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if x != nil {
		return x.Type
	}
	return ATBUS_COMPRESSION_ALGORITHM_TYPE_ATBUS_COMPRESSION_ALGORITHM_NONE
}

func (x *MessageHeadCompression) GetOriginalSize() uint64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

type MessageHead struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type        int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ResultCode  int32                  `protobuf:"zigzag32,3,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Sequence    uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceBusId uint64                 `protobuf:"varint,5,opt,name=source_bus_id,json=sourceBusId,proto3" json:"source_bus_id,omitempty"`
	Crypto      *MessageHeadCrypto     `protobuf:"bytes,6,opt,name=crypto,proto3" json:"crypto,omitempty"`
	// 加密算法：加密会带字典头部，如果数据很小，加密后反而会扩大尺寸。此时不如不加密。
	// 所以我们每个包是动态决定是否加密的，通过此字段告诉对端如何解包。
	Compression *MessageHeadCompression `protobuf:"bytes,7,opt,name=compression,proto3" json:"compression,omitempty"`
	// body size without padding
	BodySize      uint64 `protobuf:"varint,9,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHead) Reset() {
	*x = MessageHead{}
	mi := &file_libatbus_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHead) ProtoMessage() {}

func (x *MessageHead) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHead.ProtoReflect.Descriptor instead.
func (*MessageHead) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MessageHead) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MessageHead) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageHead) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *MessageHead) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MessageHead) GetSourceBusId() uint64 {
	if x != nil {
		return x.SourceBusId
	}
	return 0
}

func (x *MessageHead) GetCrypto() *MessageHeadCrypto {
	if x != nil {
		return x.Crypto
	}
	return nil
}

func (x *MessageHead) GetCompression() *MessageHeadCompression {
	if x != nil {
		return x.Compression
	}
	return nil
}

func (x *MessageHead) GetBodySize() uint64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

type MessageBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*MessageBody_CustomCommandReq
	//	*MessageBody_CustomCommandRsp
	//	*MessageBody_DataTransformReq
	//	*MessageBody_DataTransformRsp
	//	*MessageBody_NodeRegisterReq
	//	*MessageBody_NodeRegisterRsp
	//	*MessageBody_NodePingReq
	//	*MessageBody_NodePongRsp
	//	*MessageBody_HandshakeConfirm
	MessageType   isMessageBody_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_libatbus_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_libatbus_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_libatbus_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *MessageBody) GetMessageType() isMessageBody_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MessageBody) GetCustomCommandReq() *CustomCommandData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_CustomCommandReq); ok {
			return x.CustomCommandReq
		}
	}
	return nil
}

func (x *MessageBody) GetCustomCommandRsp() *CustomCommandData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_CustomCommandRsp); ok {
			return x.CustomCommandRsp
		}
	}
	return nil
}

func (x *MessageBody) GetDataTransformReq() *ForwardData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_DataTransformReq); ok {
			return x.DataTransformReq
		}
	}
	return nil
}

func (x *MessageBody) GetDataTransformRsp() *ForwardData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_DataTransformRsp); ok {
			return x.DataTransformRsp
		}
	}
	return nil
}

func (x *MessageBody) GetNodeRegisterReq() *RegisterData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_NodeRegisterReq); ok {
			return x.NodeRegisterReq
		}
	}
	return nil
}

func (x *MessageBody) GetNodeRegisterRsp() *RegisterData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_NodeRegisterRsp); ok {
			return x.NodeRegisterRsp
		}
	}
	return nil
}

func (x *MessageBody) GetNodePingReq() *PingData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_NodePingReq); ok {
			return x.NodePingReq
		}
	}
	return nil
}

func (x *MessageBody) GetNodePongRsp() *PingData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_NodePongRsp); ok {
			return x.NodePongRsp
		}
	}
	return nil
}

func (x *MessageBody) GetHandshakeConfirm() *HandshakeConfirmData {
	if x != nil {
		if x, ok := x.MessageType.(*MessageBody_HandshakeConfirm); ok {
			return x.HandshakeConfirm
		}
	}
	return nil
}

type isMessageBody_MessageType interface {
	isMessageBody_MessageType()
}

type MessageBody_CustomCommandReq struct {
	CustomCommandReq *CustomCommandData `protobuf:"bytes,1,opt,name=custom_command_req,json=customCommandReq,proto3,oneof"`
}

type MessageBody_CustomCommandRsp struct {
	CustomCommandRsp *CustomCommandData `protobuf:"bytes,2,opt,name=custom_command_rsp,json=customCommandRsp,proto3,oneof"`
}

type MessageBody_DataTransformReq struct {
	DataTransformReq *ForwardData `protobuf:"bytes,3,opt,name=data_transform_req,json=dataTransformReq,proto3,oneof"`
}

type MessageBody_DataTransformRsp struct {
	DataTransformRsp *ForwardData `protobuf:"bytes,4,opt,name=data_transform_rsp,json=dataTransformRsp,proto3,oneof"`
}

type MessageBody_NodeRegisterReq struct {
	NodeRegisterReq *RegisterData `protobuf:"bytes,5,opt,name=node_register_req,json=nodeRegisterReq,proto3,oneof"`
}

type MessageBody_NodeRegisterRsp struct {
	NodeRegisterRsp *RegisterData `protobuf:"bytes,6,opt,name=node_register_rsp,json=nodeRegisterRsp,proto3,oneof"`
}

type MessageBody_NodePingReq struct {
	NodePingReq *PingData `protobuf:"bytes,7,opt,name=node_ping_req,json=nodePingReq,proto3,oneof"`
}

type MessageBody_NodePongRsp struct {
	NodePongRsp *PingData `protobuf:"bytes,8,opt,name=node_pong_rsp,json=nodePongRsp,proto3,oneof"`
}

type MessageBody_HandshakeConfirm struct {
	HandshakeConfirm *HandshakeConfirmData `protobuf:"bytes,9,opt,name=handshake_confirm,json=handshakeConfirm,proto3,oneof"`
}

func (*MessageBody_CustomCommandReq) isMessageBody_MessageType() {}

func (*MessageBody_CustomCommandRsp) isMessageBody_MessageType() {}

func (*MessageBody_DataTransformReq) isMessageBody_MessageType() {}

func (*MessageBody_DataTransformRsp) isMessageBody_MessageType() {}

func (*MessageBody_NodeRegisterReq) isMessageBody_MessageType() {}

func (*MessageBody_NodeRegisterRsp) isMessageBody_MessageType() {}

func (*MessageBody_NodePingReq) isMessageBody_MessageType() {}

func (*MessageBody_NodePongRsp) isMessageBody_MessageType() {}

func (*MessageBody_HandshakeConfirm) isMessageBody_MessageType() {}

var File_libatbus_protocol_proto protoreflect.FileDescriptor

const file_libatbus_protocol_proto_rawDesc = "" +
	"\n" +
	"\x17libatbus_protocol.proto\x12\x1aatframework.atbus.protocol\"\xfd\x02\n" +
	"\x15crypto_handshake_data\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12N\n" +
	"\x04type\x18\x02 \x01(\x0e2:.atframework.atbus.protocol.ATBUS_CRYPTO_KEY_EXCHANGE_TYPER\x04type\x12L\n" +
	"\bkdf_type\x18\x03 \x03(\x0e21.atframework.atbus.protocol.ATBUS_CRYPTO_KDF_TYPER\akdfType\x12W\n" +
	"\n" +
	"algorithms\x18\x04 \x03(\x0e27.atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPER\n" +
	"algorithms\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\x12\x17\n" +
	"\aiv_size\x18\v \x01(\rR\x06ivSize\x12\x19\n" +
	"\btag_size\x18\x15 \x01(\rR\atagSize\"'\n" +
	"\x13custom_command_argv\x12\x10\n" +
	"\x03arg\x18\x01 \x01(\fR\x03arg\"\xbe\x01\n" +
	"\x13custom_command_data\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12K\n" +
	"\bcommands\x18\x02 \x03(\v2/.atframework.atbus.protocol.custom_command_argvR\bcommands\x12F\n" +
	"\n" +
	"access_key\x18\x03 \x01(\v2'.atframework.atbus.protocol.access_dataR\taccessKey\"z\n" +
	"\fforward_data\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x16\n" +
	"\x06router\x18\x03 \x03(\x04R\x06router\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"\xd5\x01\n" +
	"\vaccess_data\x12Z\n" +
	"\talgorithm\x18\x01 \x01(\x0e2<.atframework.atbus.protocol.ATBUS_ACCESS_DATA_ALGORITHM_TYPER\talgorithm\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06nonce1\x18\x03 \x01(\x04R\x06nonce1\x12\x16\n" +
	"\x06nonce2\x18\x04 \x01(\x04R\x06nonce2\x12\x1c\n" +
	"\tsignature\x18\t \x03(\fR\tsignature\"(\n" +
	"\fchannel_data\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x88\x01\n" +
	"\tping_data\x12\x1d\n" +
	"\n" +
	"time_point\x18\x01 \x01(\x03R\ttimePoint\x12\\\n" +
	"\x10crypto_handshake\x18\x02 \x01(\v21.atframework.atbus.protocol.crypto_handshake_dataR\x0fcryptoHandshake\"\xb4\x04\n" +
	"\rregister_data\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\x04R\x05busId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12D\n" +
	"\bchannels\x18\x04 \x03(\v2(.atframework.atbus.protocol.channel_dataR\bchannels\x128\n" +
	"\x18supported_channel_schema\x18\x05 \x03(\tR\x16supportedChannelSchema\x12\x84\x01\n" +
	"\x1fsupported_compression_algorithm\x18\x06 \x03(\x0e2<.atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPER\x1dsupportedCompressionAlgorithm\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12F\n" +
	"\n" +
	"access_key\x18\b \x01(\v2'.atframework.atbus.protocol.access_dataR\taccessKey\x12\x1b\n" +
	"\thash_code\x18\n" +
	" \x01(\tR\bhashCode\x12\\\n" +
	"\x10crypto_handshake\x18\v \x01(\v21.atframework.atbus.protocol.crypto_handshake_dataR\x0fcryptoHandshake\"4\n" +
	"\x16handshake_confirm_data\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\x8e\x01\n" +
	"\x13message_head_crypto\x12U\n" +
	"\talgorithm\x18\x01 \x01(\x0e27.atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPER\talgorithm\x12\x0e\n" +
	"\x02iv\x18\x02 \x01(\fR\x02iv\x12\x10\n" +
	"\x03aad\x18\v \x01(\fR\x03aad\"\x91\x01\n" +
	"\x18message_head_compression\x12P\n" +
	"\x04type\x18\x01 \x01(\x0e2<.atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPER\x04type\x12#\n" +
	"\roriginal_size\x18\x02 \x01(\x04R\foriginalSize\"\xdb\x02\n" +
	"\fmessage_head\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1f\n" +
	"\vresult_code\x18\x03 \x01(\x11R\n" +
	"resultCode\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\"\n" +
	"\rsource_bus_id\x18\x05 \x01(\x04R\vsourceBusId\x12G\n" +
	"\x06crypto\x18\x06 \x01(\v2/.atframework.atbus.protocol.message_head_cryptoR\x06crypto\x12V\n" +
	"\vcompression\x18\a \x01(\v24.atframework.atbus.protocol.message_head_compressionR\vcompression\x12\x1b\n" +
	"\tbody_size\x18\t \x01(\x04R\bbodySize\"\xc3\x06\n" +
	"\fmessage_body\x12_\n" +
	"\x12custom_command_req\x18\x01 \x01(\v2/.atframework.atbus.protocol.custom_command_dataH\x00R\x10customCommandReq\x12_\n" +
	"\x12custom_command_rsp\x18\x02 \x01(\v2/.atframework.atbus.protocol.custom_command_dataH\x00R\x10customCommandRsp\x12X\n" +
	"\x12data_transform_req\x18\x03 \x01(\v2(.atframework.atbus.protocol.forward_dataH\x00R\x10dataTransformReq\x12X\n" +
	"\x12data_transform_rsp\x18\x04 \x01(\v2(.atframework.atbus.protocol.forward_dataH\x00R\x10dataTransformRsp\x12W\n" +
	"\x11node_register_req\x18\x05 \x01(\v2).atframework.atbus.protocol.register_dataH\x00R\x0fnodeRegisterReq\x12W\n" +
	"\x11node_register_rsp\x18\x06 \x01(\v2).atframework.atbus.protocol.register_dataH\x00R\x0fnodeRegisterRsp\x12K\n" +
	"\rnode_ping_req\x18\a \x01(\v2%.atframework.atbus.protocol.ping_dataH\x00R\vnodePingReq\x12K\n" +
	"\rnode_pong_rsp\x18\b \x01(\v2%.atframework.atbus.protocol.ping_dataH\x00R\vnodePongRsp\x12a\n" +
	"\x11handshake_confirm\x18\t \x01(\v22.atframework.atbus.protocol.handshake_confirm_dataH\x00R\x10handshakeConfirmB\x0e\n" +
	"\fmessage_type*|\n" +
	"\x14ATBUS_PROTOCOL_CONST\x12 \n" +
	"\x1cATBUS_PROTOCOL_CONST_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16ATBUS_PROTOCOL_VERSION\x10\x03\x12\"\n" +
	"\x1eATBUS_PROTOCOL_MINIMAL_VERSION\x10\x03\x1a\x02\x10\x01*]\n" +
	"\x1cATBUS_FORWARD_DATA_FLAG_TYPE\x12\x1a\n" +
	"\x16FORWARD_DATA_FLAG_NONE\x10\x00\x12!\n" +
	"\x1dFORWARD_DATA_FLAG_REQUIRE_RSP\x10\x01*O\n" +
	" ATBUS_ACCESS_DATA_ALGORITHM_TYPE\x12+\n" +
	"'ATBUS_ACCESS_DATA_ALGORITHM_HMAC_SHA256\x10\x00*9\n" +
	"\x15ATBUS_CRYPTO_KDF_TYPE\x12 \n" +
	"\x1cATBUS_CRYPTO_KDF_HKDF_SHA256\x10\x00*\xdc\x03\n" +
	"\x1bATBUS_CRYPTO_ALGORITHM_TYPE\x12\x1f\n" +
	"\x1bATBUS_CRYPTO_ALGORITHM_NONE\x10\x00\x12 \n" +
	"\x1cATBUS_CRYPTO_ALGORITHM_XXTEA\x10\x01\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_128_CBC\x10\v\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_192_CBC\x10\f\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_256_CBC\x10\r\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_128_GCM\x10\x0e\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_192_GCM\x10\x0f\x12&\n" +
	"\"ATBUS_CRYPTO_ALGORITHM_AES_256_GCM\x10\x10\x12#\n" +
	"\x1fATBUS_CRYPTO_ALGORITHM_CHACHA20\x10\x1f\x121\n" +
	"-ATBUS_CRYPTO_ALGORITHM_CHACHA20_POLY1305_IETF\x10 \x122\n" +
	".ATBUS_CRYPTO_ALGORITHM_XCHACHA20_POLY1305_IETF\x10!*\xe5\x01\n" +
	"\x1eATBUS_CRYPTO_KEY_EXCHANGE_TYPE\x12\"\n" +
	"\x1eATBUS_CRYPTO_KEY_EXCHANGE_NONE\x10\x00\x12$\n" +
	" ATBUS_CRYPTO_KEY_EXCHANGE_X25519\x10\x01\x12'\n" +
	"#ATBUS_CRYPTO_KEY_EXCHANGE_SECP256R1\x10\x02\x12'\n" +
	"#ATBUS_CRYPTO_KEY_EXCHANGE_SECP384R1\x10\x03\x12'\n" +
	"#ATBUS_CRYPTO_KEY_EXCHANGE_SECP521R1\x10\x04*\xe4\x01\n" +
	" ATBUS_COMPRESSION_ALGORITHM_TYPE\x12$\n" +
	" ATBUS_COMPRESSION_ALGORITHM_NONE\x10\x00\x12$\n" +
	" ATBUS_COMPRESSION_ALGORITHM_ZSTD\x10d\x12$\n" +
	"\x1fATBUS_COMPRESSION_ALGORITHM_LZ4\x10\xc8\x01\x12'\n" +
	"\"ATBUS_COMPRESSION_ALGORITHM_SNAPPY\x10\xac\x02\x12%\n" +
	" ATBUS_COMPRESSION_ALGORITHM_ZLIB\x10\x90\x03*\xa4\x02\n" +
	"\x17ATBUS_COMPRESSION_LEVEL\x12#\n" +
	"\x1fATBUS_COMPRESSION_LEVEL_DEFAULT\x10\x00\x12#\n" +
	"\x1fATBUS_COMPRESSION_LEVEL_STORAGE\x10d\x12!\n" +
	"\x1cATBUS_COMPRESSION_LEVEL_FAST\x10\xc8\x01\x12$\n" +
	"\x1fATBUS_COMPRESSION_LEVEL_LOW_CPU\x10\xac\x02\x12%\n" +
	" ATBUS_COMPRESSION_LEVEL_BALANCED\x10\x90\x03\x12'\n" +
	"\"ATBUS_COMPRESSION_LEVEL_HIGH_RATIO\x10\xf4\x03\x12&\n" +
	"!ATBUS_COMPRESSION_LEVEL_MAX_RATIO\x10\xd8\x04B2H\x01Z+github.com/atframework/libatbus-go/protocol\xf8\x01\x01b\x06proto3"

var (
	file_libatbus_protocol_proto_rawDescOnce sync.Once
	file_libatbus_protocol_proto_rawDescData []byte
)

func file_libatbus_protocol_proto_rawDescGZIP() []byte {
	file_libatbus_protocol_proto_rawDescOnce.Do(func() {
		file_libatbus_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libatbus_protocol_proto_rawDesc), len(file_libatbus_protocol_proto_rawDesc)))
	})
	return file_libatbus_protocol_proto_rawDescData
}

var file_libatbus_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_libatbus_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_libatbus_protocol_proto_goTypes = []any{
	(ATBUS_PROTOCOL_CONST)(0),             // 0: atframework.atbus.protocol.ATBUS_PROTOCOL_CONST
	(ATBUS_FORWARD_DATA_FLAG_TYPE)(0),     // 1: atframework.atbus.protocol.ATBUS_FORWARD_DATA_FLAG_TYPE
	(ATBUS_ACCESS_DATA_ALGORITHM_TYPE)(0), // 2: atframework.atbus.protocol.ATBUS_ACCESS_DATA_ALGORITHM_TYPE
	(ATBUS_CRYPTO_KDF_TYPE)(0),            // 3: atframework.atbus.protocol.ATBUS_CRYPTO_KDF_TYPE
	(ATBUS_CRYPTO_ALGORITHM_TYPE)(0),      // 4: atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPE
	(ATBUS_CRYPTO_KEY_EXCHANGE_TYPE)(0),   // 5: atframework.atbus.protocol.ATBUS_CRYPTO_KEY_EXCHANGE_TYPE
	(ATBUS_COMPRESSION_ALGORITHM_TYPE)(0), // 6: atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPE
	(ATBUS_COMPRESSION_LEVEL)(0),          // 7: atframework.atbus.protocol.ATBUS_COMPRESSION_LEVEL
	(*CryptoHandshakeData)(nil),           // 8: atframework.atbus.protocol.crypto_handshake_data
	(*CustomCommandArgv)(nil),             // 9: atframework.atbus.protocol.custom_command_argv
	(*CustomCommandData)(nil),             // 10: atframework.atbus.protocol.custom_command_data
	(*ForwardData)(nil),                   // 11: atframework.atbus.protocol.forward_data
	(*AccessData)(nil),                    // 12: atframework.atbus.protocol.access_data
	(*ChannelData)(nil),                   // 13: atframework.atbus.protocol.channel_data
	(*PingData)(nil),                      // 14: atframework.atbus.protocol.ping_data
	(*RegisterData)(nil),                  // 15: atframework.atbus.protocol.register_data
	(*HandshakeConfirmData)(nil),          // 16: atframework.atbus.protocol.handshake_confirm_data
	(*MessageHeadCrypto)(nil),             // 17: atframework.atbus.protocol.message_head_crypto
	(*MessageHeadCompression)(nil),        // 18: atframework.atbus.protocol.message_head_compression
	(*MessageHead)(nil),                   // 19: atframework.atbus.protocol.message_head
	(*MessageBody)(nil),                   // 20: atframework.atbus.protocol.message_body
}
var file_libatbus_protocol_proto_depIdxs = []int32{
	5,  // 0: atframework.atbus.protocol.crypto_handshake_data.type:type_name -> atframework.atbus.protocol.ATBUS_CRYPTO_KEY_EXCHANGE_TYPE
	3,  // 1: atframework.atbus.protocol.crypto_handshake_data.kdf_type:type_name -> atframework.atbus.protocol.ATBUS_CRYPTO_KDF_TYPE
	4,  // 2: atframework.atbus.protocol.crypto_handshake_data.algorithms:type_name -> atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPE
	9,  // 3: atframework.atbus.protocol.custom_command_data.commands:type_name -> atframework.atbus.protocol.custom_command_argv
	12, // 4: atframework.atbus.protocol.custom_command_data.access_key:type_name -> atframework.atbus.protocol.access_data
	2,  // 5: atframework.atbus.protocol.access_data.algorithm:type_name -> atframework.atbus.protocol.ATBUS_ACCESS_DATA_ALGORITHM_TYPE
	8,  // 6: atframework.atbus.protocol.ping_data.crypto_handshake:type_name -> atframework.atbus.protocol.crypto_handshake_data
	13, // 7: atframework.atbus.protocol.register_data.channels:type_name -> atframework.atbus.protocol.channel_data
	6,  // 8: atframework.atbus.protocol.register_data.supported_compression_algorithm:type_name -> atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPE
	12, // 9: atframework.atbus.protocol.register_data.access_key:type_name -> atframework.atbus.protocol.access_data
	8,  // 10: atframework.atbus.protocol.register_data.crypto_handshake:type_name -> atframework.atbus.protocol.crypto_handshake_data
	4,  // 11: atframework.atbus.protocol.message_head_crypto.algorithm:type_name -> atframework.atbus.protocol.ATBUS_CRYPTO_ALGORITHM_TYPE
	6,  // 12: atframework.atbus.protocol.message_head_compression.type:type_name -> atframework.atbus.protocol.ATBUS_COMPRESSION_ALGORITHM_TYPE
	17, // 13: atframework.atbus.protocol.message_head.crypto:type_name -> atframework.atbus.protocol.message_head_crypto
	18, // 14: atframework.atbus.protocol.message_head.compression:type_name -> atframework.atbus.protocol.message_head_compression
	10, // 15: atframework.atbus.protocol.message_body.custom_command_req:type_name -> atframework.atbus.protocol.custom_command_data
	10, // 16: atframework.atbus.protocol.message_body.custom_command_rsp:type_name -> atframework.atbus.protocol.custom_command_data
	11, // 17: atframework.atbus.protocol.message_body.data_transform_req:type_name -> atframework.atbus.protocol.forward_data
	11, // 18: atframework.atbus.protocol.message_body.data_transform_rsp:type_name -> atframework.atbus.protocol.forward_data
	15, // 19: atframework.atbus.protocol.message_body.node_register_req:type_name -> atframework.atbus.protocol.register_data
	15, // 20: atframework.atbus.protocol.message_body.node_register_rsp:type_name -> atframework.atbus.protocol.register_data
	14, // 21: atframework.atbus.protocol.message_body.node_ping_req:type_name -> atframework.atbus.protocol.ping_data
	14, // 22: atframework.atbus.protocol.message_body.node_pong_rsp:type_name -> atframework.atbus.protocol.ping_data
	16, // 23: atframework.atbus.protocol.message_body.handshake_confirm:type_name -> atframework.atbus.protocol.handshake_confirm_data
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_libatbus_protocol_proto_init() }
func file_libatbus_protocol_proto_init() {
	if File_libatbus_protocol_proto != nil {
		return
	}
	file_libatbus_protocol_proto_msgTypes[12].OneofWrappers = []any{
		(*MessageBody_CustomCommandReq)(nil),
		(*MessageBody_CustomCommandRsp)(nil),
		(*MessageBody_DataTransformReq)(nil),
		(*MessageBody_DataTransformRsp)(nil),
		(*MessageBody_NodeRegisterReq)(nil),
		(*MessageBody_NodeRegisterRsp)(nil),
		(*MessageBody_NodePingReq)(nil),
		(*MessageBody_NodePongRsp)(nil),
		(*MessageBody_HandshakeConfirm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libatbus_protocol_proto_rawDesc), len(file_libatbus_protocol_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libatbus_protocol_proto_goTypes,
		DependencyIndexes: file_libatbus_protocol_proto_depIdxs,
		EnumInfos:         file_libatbus_protocol_proto_enumTypes,
		MessageInfos:      file_libatbus_protocol_proto_msgTypes,
	}.Build()
	File_libatbus_protocol_proto = out.File
	file_libatbus_protocol_proto_goTypes = nil
	file_libatbus_protocol_proto_depIdxs = nil
}
