// Code generated by protoc-gen-mutable. DO NOT EDIT.
// source: libatbus_protocol.proto

package protocol

import "google.golang.org/protobuf/proto"
import "log/slog"
import pu "github.com/atframework/atframe-utils-go/proto_utility"
import lu "github.com/atframework/atframe-utils-go/lang_utility"
import protoreflect "google.golang.org/protobuf/reflect/protoreflect"

type innerFile_libatbus_protocol_protoReadonlyMessage interface {
	Descriptor() protoreflect.MessageDescriptor
	Type() protoreflect.MessageType
	New() protoreflect.Message
	Interface() protoreflect.ProtoMessage
	Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool)
	Has(protoreflect.FieldDescriptor) bool
	Get(protoreflect.FieldDescriptor) protoreflect.Value
	WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor
	GetUnknown() protoreflect.RawFields
	IsValid() bool
}

// ===== Clone methods for CryptoHandshakeData ===== Message ====
func (m *CryptoHandshakeData) Clone() *CryptoHandshakeData {
	if m == nil {
		return new(CryptoHandshakeData)
	}
	return proto.Clone(m).(*CryptoHandshakeData)
}

// ===== Merge methods for CryptoHandshakeData ===== Message ====
func (m *CryptoHandshakeData) Merge(src *CryptoHandshakeData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for CryptoHandshakeData ===== Message ====
func (m *CryptoHandshakeData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for CryptoHandshakeData ===== Message =====
func (_ *CryptoHandshakeData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[CryptoHandshakeData]()
}

// ===== Readonly wrapper for CryptoHandshakeData ===== Message ====
type Readonly_CryptoHandshakeData struct {
	protoData       *CryptoHandshakeData
	fieldSequence   uint64
	fieldType       ATBUS_CRYPTO_KEY_EXCHANGE_TYPE
	fieldKdfType    []ATBUS_CRYPTO_KDF_TYPE
	fieldAlgorithms []ATBUS_CRYPTO_ALGORITHM_TYPE
	fieldPublicKey  []byte
	fieldIvSize     uint32
	fieldTagSize    uint32
}

func (r *Readonly_CryptoHandshakeData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *CryptoHandshakeData) ToReadonly() *Readonly_CryptoHandshakeData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_CryptoHandshakeData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_CryptoHandshakeData) CloneMessage() *CryptoHandshakeData {
	if r == nil {
		return new(CryptoHandshakeData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_CryptoHandshakeData) ToMessage() *CryptoHandshakeData {
	return r.CloneMessage()
}

func (r Readonly_CryptoHandshakeData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_CryptoHandshakeData) initFromProto(src *CryptoHandshakeData) {
	if r == nil || src == nil {
		return
	}
	r.fieldSequence = src.GetSequence()
	r.fieldType = src.GetType()
	if v := src.GetKdfType(); len(v) != 0 {
		copied := make([]ATBUS_CRYPTO_KDF_TYPE, len(v))
		copy(copied, v)
		r.fieldKdfType = copied
	} else {
		r.fieldKdfType = nil
	}
	if v := src.GetAlgorithms(); len(v) != 0 {
		copied := make([]ATBUS_CRYPTO_ALGORITHM_TYPE, len(v))
		copy(copied, v)
		r.fieldAlgorithms = copied
	} else {
		r.fieldAlgorithms = nil
	}
	if v := src.GetPublicKey(); len(v) != 0 {
		r.fieldPublicKey = append([]byte(nil), v...)
	} else {
		r.fieldPublicKey = nil
	}
	r.fieldIvSize = src.GetIvSize()
	r.fieldTagSize = src.GetTagSize()
}

func (r *Readonly_CryptoHandshakeData) GetSequence() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldSequence
}

func (r *Readonly_CryptoHandshakeData) GetType() ATBUS_CRYPTO_KEY_EXCHANGE_TYPE {
	if r == nil {
		var zero ATBUS_CRYPTO_KEY_EXCHANGE_TYPE
		return zero
	}
	return r.fieldType
}

func (r *Readonly_CryptoHandshakeData) GetKdfType() []ATBUS_CRYPTO_KDF_TYPE {
	if r == nil {
		var zero []ATBUS_CRYPTO_KDF_TYPE
		return zero
	}
	return r.fieldKdfType
}

func (r *Readonly_CryptoHandshakeData) GetAlgorithms() []ATBUS_CRYPTO_ALGORITHM_TYPE {
	if r == nil {
		var zero []ATBUS_CRYPTO_ALGORITHM_TYPE
		return zero
	}
	return r.fieldAlgorithms
}

func (r *Readonly_CryptoHandshakeData) GetPublicKey() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldPublicKey) == 0 {
		return r.fieldPublicKey
	}
	dup := make([]byte, len(r.fieldPublicKey))
	copy(dup, r.fieldPublicKey)
	return dup
}

func (r *Readonly_CryptoHandshakeData) GetIvSize() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldIvSize
}

func (r *Readonly_CryptoHandshakeData) GetTagSize() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldTagSize
}

// ===== Mutable methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) MutableKdfType() []ATBUS_CRYPTO_KDF_TYPE {
	if m.KdfType == nil {
		m.KdfType = []ATBUS_CRYPTO_KDF_TYPE{}
	}
	return m.KdfType
}

// ===== ReverseIfNil methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) ReverseIfNilKdfType(l int) []ATBUS_CRYPTO_KDF_TYPE {
	if m.KdfType == nil {
		m.KdfType = make([]ATBUS_CRYPTO_KDF_TYPE, 0, l)
	}
	return m.KdfType
}

// ===== Append methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) AppendKdfType(d ATBUS_CRYPTO_KDF_TYPE) {
	if m.KdfType == nil {
		m.KdfType = []ATBUS_CRYPTO_KDF_TYPE{}
	}
	m.KdfType = append(m.KdfType, d)
}

// ===== Append methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) AppendAndReverseKdfType(l int, d ATBUS_CRYPTO_KDF_TYPE) {
	if m.KdfType == nil {
		m.KdfType = make([]ATBUS_CRYPTO_KDF_TYPE, 0, l)
	}
	m.KdfType = append(m.KdfType, d)
}

// ===== Merge methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) MergeKdfType(d []ATBUS_CRYPTO_KDF_TYPE) []ATBUS_CRYPTO_KDF_TYPE {
	if m.KdfType == nil {
		m.KdfType = []ATBUS_CRYPTO_KDF_TYPE{}
	}
	m.KdfType = append(m.KdfType, d...)
	return m.KdfType
}

// ===== RemoveLast methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) RemoveLastKdfType() {
	if m.KdfType == nil {
		m.KdfType = []ATBUS_CRYPTO_KDF_TYPE{}
	}
	if len(m.KdfType) != 0 {
		m.KdfType = m.KdfType[:len(m.KdfType)-1]
	}
}

// ===== Mutable methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) MutableAlgorithms() []ATBUS_CRYPTO_ALGORITHM_TYPE {
	if m.Algorithms == nil {
		m.Algorithms = []ATBUS_CRYPTO_ALGORITHM_TYPE{}
	}
	return m.Algorithms
}

// ===== ReverseIfNil methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) ReverseIfNilAlgorithms(l int) []ATBUS_CRYPTO_ALGORITHM_TYPE {
	if m.Algorithms == nil {
		m.Algorithms = make([]ATBUS_CRYPTO_ALGORITHM_TYPE, 0, l)
	}
	return m.Algorithms
}

// ===== Append methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) AppendAlgorithms(d ATBUS_CRYPTO_ALGORITHM_TYPE) {
	if m.Algorithms == nil {
		m.Algorithms = []ATBUS_CRYPTO_ALGORITHM_TYPE{}
	}
	m.Algorithms = append(m.Algorithms, d)
}

// ===== Append methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) AppendAndReverseAlgorithms(l int, d ATBUS_CRYPTO_ALGORITHM_TYPE) {
	if m.Algorithms == nil {
		m.Algorithms = make([]ATBUS_CRYPTO_ALGORITHM_TYPE, 0, l)
	}
	m.Algorithms = append(m.Algorithms, d)
}

// ===== Merge methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) MergeAlgorithms(d []ATBUS_CRYPTO_ALGORITHM_TYPE) []ATBUS_CRYPTO_ALGORITHM_TYPE {
	if m.Algorithms == nil {
		m.Algorithms = []ATBUS_CRYPTO_ALGORITHM_TYPE{}
	}
	m.Algorithms = append(m.Algorithms, d...)
	return m.Algorithms
}

// ===== RemoveLast methods for CryptoHandshakeData ===== Repeated =====
func (m *CryptoHandshakeData) RemoveLastAlgorithms() {
	if m.Algorithms == nil {
		m.Algorithms = []ATBUS_CRYPTO_ALGORITHM_TYPE{}
	}
	if len(m.Algorithms) != 0 {
		m.Algorithms = m.Algorithms[:len(m.Algorithms)-1]
	}
}

// ===== Clone methods for CustomCommandArgv ===== Message ====
func (m *CustomCommandArgv) Clone() *CustomCommandArgv {
	if m == nil {
		return new(CustomCommandArgv)
	}
	return proto.Clone(m).(*CustomCommandArgv)
}

// ===== Merge methods for CustomCommandArgv ===== Message ====
func (m *CustomCommandArgv) Merge(src *CustomCommandArgv) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for CustomCommandArgv ===== Message ====
func (m *CustomCommandArgv) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for CustomCommandArgv ===== Message =====
func (_ *CustomCommandArgv) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[CustomCommandArgv]()
}

// ===== Readonly wrapper for CustomCommandArgv ===== Message ====
type Readonly_CustomCommandArgv struct {
	protoData *CustomCommandArgv
	fieldArg  []byte
}

func (r *Readonly_CustomCommandArgv) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *CustomCommandArgv) ToReadonly() *Readonly_CustomCommandArgv {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_CustomCommandArgv{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_CustomCommandArgv) CloneMessage() *CustomCommandArgv {
	if r == nil {
		return new(CustomCommandArgv)
	}
	return r.protoData.Clone()
}

func (r *Readonly_CustomCommandArgv) ToMessage() *CustomCommandArgv {
	return r.CloneMessage()
}

func (r Readonly_CustomCommandArgv) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_CustomCommandArgv) initFromProto(src *CustomCommandArgv) {
	if r == nil || src == nil {
		return
	}
	if v := src.GetArg(); len(v) != 0 {
		r.fieldArg = append([]byte(nil), v...)
	} else {
		r.fieldArg = nil
	}
}

func (r *Readonly_CustomCommandArgv) GetArg() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldArg) == 0 {
		return r.fieldArg
	}
	dup := make([]byte, len(r.fieldArg))
	copy(dup, r.fieldArg)
	return dup
}

// ===== Clone methods for CustomCommandData ===== Message ====
func (m *CustomCommandData) Clone() *CustomCommandData {
	if m == nil {
		return new(CustomCommandData)
	}
	return proto.Clone(m).(*CustomCommandData)
}

// ===== Merge methods for CustomCommandData ===== Message ====
func (m *CustomCommandData) Merge(src *CustomCommandData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for CustomCommandData ===== Message ====
func (m *CustomCommandData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for CustomCommandData ===== Message =====
func (_ *CustomCommandData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[CustomCommandData]()
}

// ===== Readonly wrapper for CustomCommandData ===== Message ====
type Readonly_CustomCommandData struct {
	protoData      *CustomCommandData
	fieldFrom      uint64
	fieldCommands  []*Readonly_CustomCommandArgv
	fieldAccessKey *Readonly_AccessData
}

func (r *Readonly_CustomCommandData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *CustomCommandData) ToReadonly() *Readonly_CustomCommandData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_CustomCommandData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_CustomCommandData) CloneMessage() *CustomCommandData {
	if r == nil {
		return new(CustomCommandData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_CustomCommandData) ToMessage() *CustomCommandData {
	return r.CloneMessage()
}

func (r Readonly_CustomCommandData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_CustomCommandData) initFromProto(src *CustomCommandData) {
	if r == nil || src == nil {
		return
	}
	r.fieldFrom = src.GetFrom()
	if v := src.GetCommands(); len(v) != 0 {
		out := make([]*Readonly_CustomCommandArgv, 0, len(v))
		for _, item := range v {
			if item == nil {
				out = append(out, nil)
				continue
			}
			out = append(out, item.ToReadonly())
		}
		r.fieldCommands = out
	} else {
		r.fieldCommands = nil
	}
	if v := src.GetAccessKey(); v != nil {
		r.fieldAccessKey = v.ToReadonly()
	} else {
		r.fieldAccessKey = nil
	}
}

func (r *Readonly_CustomCommandData) GetFrom() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldFrom
}

func (r *Readonly_CustomCommandData) GetCommands() []*Readonly_CustomCommandArgv {
	if r == nil {
		var zero []*Readonly_CustomCommandArgv
		return zero
	}
	return r.fieldCommands
}

func (r *Readonly_CustomCommandData) GetAccessKey() *Readonly_AccessData {
	if r == nil {
		var zero *Readonly_AccessData
		return zero
	}
	return r.fieldAccessKey
}

// ===== Mutable methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) MutableCommands() []*CustomCommandArgv {
	if m.Commands == nil {
		m.Commands = []*CustomCommandArgv{}
	}
	return m.Commands
}

// ===== ReverseIfNil methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) ReverseIfNilCommands(l int) []*CustomCommandArgv {
	if m.Commands == nil {
		m.Commands = make([]*CustomCommandArgv, 0, l)
	}
	return m.Commands
}

// ===== Append methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) AppendCommands(d *CustomCommandArgv) {
	if m.Commands == nil {
		m.Commands = []*CustomCommandArgv{}
	}
	m.Commands = append(m.Commands, d)
}

// ===== Append methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) AppendAndReverseCommands(l int, d *CustomCommandArgv) {
	if m.Commands == nil {
		m.Commands = make([]*CustomCommandArgv, 0, l)
	}
	m.Commands = append(m.Commands, d)
}

// ===== Add methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) AddCommands() *CustomCommandArgv {
	if m.Commands == nil {
		m.Commands = []*CustomCommandArgv{}
	}
	addValue := new(CustomCommandArgv)
	m.Commands = append(m.Commands, addValue)
	return addValue
}

// ===== Merge methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) MergeCommands(d []*CustomCommandArgv) []*CustomCommandArgv {
	if m.Commands == nil {
		m.Commands = []*CustomCommandArgv{}
	}
	m.Commands = append(m.Commands, d...)
	return m.Commands
}

// ===== RemoveLast methods for CustomCommandData ===== Repeated =====
func (m *CustomCommandData) RemoveLastCommands() {
	if m.Commands == nil {
		m.Commands = []*CustomCommandArgv{}
	}
	if len(m.Commands) != 0 {
		m.Commands = m.Commands[:len(m.Commands)-1]
	}
}

// ===== Mutable methods for CustomCommandData ===== Message =====
func (m *CustomCommandData) MutableAccessKey() *AccessData {
	if m.AccessKey == nil {
		m.AccessKey = new(AccessData)
	}
	return m.AccessKey
}

// ===== Clone methods for ForwardData ===== Message ====
func (m *ForwardData) Clone() *ForwardData {
	if m == nil {
		return new(ForwardData)
	}
	return proto.Clone(m).(*ForwardData)
}

// ===== Merge methods for ForwardData ===== Message ====
func (m *ForwardData) Merge(src *ForwardData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for ForwardData ===== Message ====
func (m *ForwardData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for ForwardData ===== Message =====
func (_ *ForwardData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[ForwardData]()
}

// ===== Readonly wrapper for ForwardData ===== Message ====
type Readonly_ForwardData struct {
	protoData    *ForwardData
	fieldFrom    uint64
	fieldTo      uint64
	fieldRouter  []uint64
	fieldContent []byte
	fieldFlags   uint32
}

func (r *Readonly_ForwardData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *ForwardData) ToReadonly() *Readonly_ForwardData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_ForwardData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_ForwardData) CloneMessage() *ForwardData {
	if r == nil {
		return new(ForwardData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_ForwardData) ToMessage() *ForwardData {
	return r.CloneMessage()
}

func (r Readonly_ForwardData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_ForwardData) initFromProto(src *ForwardData) {
	if r == nil || src == nil {
		return
	}
	r.fieldFrom = src.GetFrom()
	r.fieldTo = src.GetTo()
	if v := src.GetRouter(); len(v) != 0 {
		copied := make([]uint64, len(v))
		copy(copied, v)
		r.fieldRouter = copied
	} else {
		r.fieldRouter = nil
	}
	if v := src.GetContent(); len(v) != 0 {
		r.fieldContent = append([]byte(nil), v...)
	} else {
		r.fieldContent = nil
	}
	r.fieldFlags = src.GetFlags()
}

func (r *Readonly_ForwardData) GetFrom() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldFrom
}

func (r *Readonly_ForwardData) GetTo() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldTo
}

func (r *Readonly_ForwardData) GetRouter() []uint64 {
	if r == nil {
		var zero []uint64
		return zero
	}
	return r.fieldRouter
}

func (r *Readonly_ForwardData) GetContent() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldContent) == 0 {
		return r.fieldContent
	}
	dup := make([]byte, len(r.fieldContent))
	copy(dup, r.fieldContent)
	return dup
}

func (r *Readonly_ForwardData) GetFlags() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldFlags
}

// ===== Mutable methods for ForwardData ===== Repeated =====
func (m *ForwardData) MutableRouter() []uint64 {
	if m.Router == nil {
		m.Router = []uint64{}
	}
	return m.Router
}

// ===== ReverseIfNil methods for ForwardData ===== Repeated =====
func (m *ForwardData) ReverseIfNilRouter(l int) []uint64 {
	if m.Router == nil {
		m.Router = make([]uint64, 0, l)
	}
	return m.Router
}

// ===== Append methods for ForwardData ===== Repeated =====
func (m *ForwardData) AppendRouter(d uint64) {
	if m.Router == nil {
		m.Router = []uint64{}
	}
	m.Router = append(m.Router, d)
}

// ===== Append methods for ForwardData ===== Repeated =====
func (m *ForwardData) AppendAndReverseRouter(l int, d uint64) {
	if m.Router == nil {
		m.Router = make([]uint64, 0, l)
	}
	m.Router = append(m.Router, d)
}

// ===== Merge methods for ForwardData ===== Repeated =====
func (m *ForwardData) MergeRouter(d []uint64) []uint64 {
	if m.Router == nil {
		m.Router = []uint64{}
	}
	m.Router = append(m.Router, d...)
	return m.Router
}

// ===== RemoveLast methods for ForwardData ===== Repeated =====
func (m *ForwardData) RemoveLastRouter() {
	if m.Router == nil {
		m.Router = []uint64{}
	}
	if len(m.Router) != 0 {
		m.Router = m.Router[:len(m.Router)-1]
	}
}

// ===== Clone methods for AccessData ===== Message ====
func (m *AccessData) Clone() *AccessData {
	if m == nil {
		return new(AccessData)
	}
	return proto.Clone(m).(*AccessData)
}

// ===== Merge methods for AccessData ===== Message ====
func (m *AccessData) Merge(src *AccessData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for AccessData ===== Message ====
func (m *AccessData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for AccessData ===== Message =====
func (_ *AccessData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[AccessData]()
}

// ===== Readonly wrapper for AccessData ===== Message ====
type Readonly_AccessData struct {
	protoData      *AccessData
	fieldAlgorithm ATBUS_ACCESS_DATA_ALGORITHM_TYPE
	fieldTimestamp int64
	fieldNonce1    uint64
	fieldNonce2    uint64
	fieldSignature [][]byte
}

func (r *Readonly_AccessData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *AccessData) ToReadonly() *Readonly_AccessData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_AccessData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_AccessData) CloneMessage() *AccessData {
	if r == nil {
		return new(AccessData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_AccessData) ToMessage() *AccessData {
	return r.CloneMessage()
}

func (r Readonly_AccessData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_AccessData) initFromProto(src *AccessData) {
	if r == nil || src == nil {
		return
	}
	r.fieldAlgorithm = src.GetAlgorithm()
	r.fieldTimestamp = src.GetTimestamp()
	r.fieldNonce1 = src.GetNonce1()
	r.fieldNonce2 = src.GetNonce2()
	if v := src.GetSignature(); len(v) != 0 {
		out := make([][]byte, len(v))
		for i := range v {
			if len(v[i]) != 0 {
				out[i] = append([]byte(nil), v[i]...)
			}
		}
		r.fieldSignature = out
	} else {
		r.fieldSignature = nil
	}
}

func (r *Readonly_AccessData) GetAlgorithm() ATBUS_ACCESS_DATA_ALGORITHM_TYPE {
	if r == nil {
		var zero ATBUS_ACCESS_DATA_ALGORITHM_TYPE
		return zero
	}
	return r.fieldAlgorithm
}

func (r *Readonly_AccessData) GetTimestamp() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldTimestamp
}

func (r *Readonly_AccessData) GetNonce1() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldNonce1
}

func (r *Readonly_AccessData) GetNonce2() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldNonce2
}

func (r *Readonly_AccessData) GetSignature() [][]byte {
	if r == nil {
		var zero [][]byte
		return zero
	}
	return r.fieldSignature
}

// ===== Mutable methods for AccessData ===== Repeated =====
func (m *AccessData) MutableSignature() [][]byte {
	if m.Signature == nil {
		m.Signature = [][]byte{}
	}
	return m.Signature
}

// ===== ReverseIfNil methods for AccessData ===== Repeated =====
func (m *AccessData) ReverseIfNilSignature(l int) [][]byte {
	if m.Signature == nil {
		m.Signature = make([][]byte, 0, l)
	}
	return m.Signature
}

// ===== Append methods for AccessData ===== Repeated =====
func (m *AccessData) AppendSignature(d []byte) {
	if m.Signature == nil {
		m.Signature = [][]byte{}
	}
	m.Signature = append(m.Signature, d)
}

// ===== Append methods for AccessData ===== Repeated =====
func (m *AccessData) AppendAndReverseSignature(l int, d []byte) {
	if m.Signature == nil {
		m.Signature = make([][]byte, 0, l)
	}
	m.Signature = append(m.Signature, d)
}

// ===== Merge methods for AccessData ===== Repeated =====
func (m *AccessData) MergeSignature(d [][]byte) [][]byte {
	if m.Signature == nil {
		m.Signature = [][]byte{}
	}
	m.Signature = append(m.Signature, d...)
	return m.Signature
}

// ===== RemoveLast methods for AccessData ===== Repeated =====
func (m *AccessData) RemoveLastSignature() {
	if m.Signature == nil {
		m.Signature = [][]byte{}
	}
	if len(m.Signature) != 0 {
		m.Signature = m.Signature[:len(m.Signature)-1]
	}
}

// ===== Clone methods for ChannelData ===== Message ====
func (m *ChannelData) Clone() *ChannelData {
	if m == nil {
		return new(ChannelData)
	}
	return proto.Clone(m).(*ChannelData)
}

// ===== Merge methods for ChannelData ===== Message ====
func (m *ChannelData) Merge(src *ChannelData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for ChannelData ===== Message ====
func (m *ChannelData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for ChannelData ===== Message =====
func (_ *ChannelData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[ChannelData]()
}

// ===== Readonly wrapper for ChannelData ===== Message ====
type Readonly_ChannelData struct {
	protoData    *ChannelData
	fieldAddress string
}

func (r *Readonly_ChannelData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *ChannelData) ToReadonly() *Readonly_ChannelData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_ChannelData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_ChannelData) CloneMessage() *ChannelData {
	if r == nil {
		return new(ChannelData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_ChannelData) ToMessage() *ChannelData {
	return r.CloneMessage()
}

func (r Readonly_ChannelData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_ChannelData) initFromProto(src *ChannelData) {
	if r == nil || src == nil {
		return
	}
	r.fieldAddress = src.GetAddress()
}

func (r *Readonly_ChannelData) GetAddress() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldAddress
}

// ===== Clone methods for PingData ===== Message ====
func (m *PingData) Clone() *PingData {
	if m == nil {
		return new(PingData)
	}
	return proto.Clone(m).(*PingData)
}

// ===== Merge methods for PingData ===== Message ====
func (m *PingData) Merge(src *PingData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for PingData ===== Message ====
func (m *PingData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for PingData ===== Message =====
func (_ *PingData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[PingData]()
}

// ===== Readonly wrapper for PingData ===== Message ====
type Readonly_PingData struct {
	protoData            *PingData
	fieldTimePoint       int64
	fieldCryptoHandshake *Readonly_CryptoHandshakeData
}

func (r *Readonly_PingData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *PingData) ToReadonly() *Readonly_PingData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_PingData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_PingData) CloneMessage() *PingData {
	if r == nil {
		return new(PingData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_PingData) ToMessage() *PingData {
	return r.CloneMessage()
}

func (r Readonly_PingData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_PingData) initFromProto(src *PingData) {
	if r == nil || src == nil {
		return
	}
	r.fieldTimePoint = src.GetTimePoint()
	if v := src.GetCryptoHandshake(); v != nil {
		r.fieldCryptoHandshake = v.ToReadonly()
	} else {
		r.fieldCryptoHandshake = nil
	}
}

func (r *Readonly_PingData) GetTimePoint() int64 {
	if r == nil {
		var zero int64
		return zero
	}
	return r.fieldTimePoint
}

func (r *Readonly_PingData) GetCryptoHandshake() *Readonly_CryptoHandshakeData {
	if r == nil {
		var zero *Readonly_CryptoHandshakeData
		return zero
	}
	return r.fieldCryptoHandshake
}

// ===== Mutable methods for PingData ===== Message =====
func (m *PingData) MutableCryptoHandshake() *CryptoHandshakeData {
	if m.CryptoHandshake == nil {
		m.CryptoHandshake = new(CryptoHandshakeData)
	}
	return m.CryptoHandshake
}

// ===== Clone methods for RegisterData ===== Message ====
func (m *RegisterData) Clone() *RegisterData {
	if m == nil {
		return new(RegisterData)
	}
	return proto.Clone(m).(*RegisterData)
}

// ===== Merge methods for RegisterData ===== Message ====
func (m *RegisterData) Merge(src *RegisterData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for RegisterData ===== Message ====
func (m *RegisterData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for RegisterData ===== Message =====
func (_ *RegisterData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[RegisterData]()
}

// ===== Readonly wrapper for RegisterData ===== Message ====
type Readonly_RegisterData struct {
	protoData                          *RegisterData
	fieldBusId                         uint64
	fieldPid                           int32
	fieldHostname                      string
	fieldChannels                      []*Readonly_ChannelData
	fieldSupportedChannelSchema        []string
	fieldSupportedCompressionAlgorithm []ATBUS_COMPRESSION_ALGORITHM_TYPE
	fieldFlags                         uint32
	fieldAccessKey                     *Readonly_AccessData
	fieldHashCode                      string
	fieldCryptoHandshake               *Readonly_CryptoHandshakeData
}

func (r *Readonly_RegisterData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *RegisterData) ToReadonly() *Readonly_RegisterData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_RegisterData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_RegisterData) CloneMessage() *RegisterData {
	if r == nil {
		return new(RegisterData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_RegisterData) ToMessage() *RegisterData {
	return r.CloneMessage()
}

func (r Readonly_RegisterData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_RegisterData) initFromProto(src *RegisterData) {
	if r == nil || src == nil {
		return
	}
	r.fieldBusId = src.GetBusId()
	r.fieldPid = src.GetPid()
	r.fieldHostname = src.GetHostname()
	if v := src.GetChannels(); len(v) != 0 {
		out := make([]*Readonly_ChannelData, 0, len(v))
		for _, item := range v {
			if item == nil {
				out = append(out, nil)
				continue
			}
			out = append(out, item.ToReadonly())
		}
		r.fieldChannels = out
	} else {
		r.fieldChannels = nil
	}
	if v := src.GetSupportedChannelSchema(); len(v) != 0 {
		copied := make([]string, len(v))
		copy(copied, v)
		r.fieldSupportedChannelSchema = copied
	} else {
		r.fieldSupportedChannelSchema = nil
	}
	if v := src.GetSupportedCompressionAlgorithm(); len(v) != 0 {
		copied := make([]ATBUS_COMPRESSION_ALGORITHM_TYPE, len(v))
		copy(copied, v)
		r.fieldSupportedCompressionAlgorithm = copied
	} else {
		r.fieldSupportedCompressionAlgorithm = nil
	}
	r.fieldFlags = src.GetFlags()
	if v := src.GetAccessKey(); v != nil {
		r.fieldAccessKey = v.ToReadonly()
	} else {
		r.fieldAccessKey = nil
	}
	r.fieldHashCode = src.GetHashCode()
	if v := src.GetCryptoHandshake(); v != nil {
		r.fieldCryptoHandshake = v.ToReadonly()
	} else {
		r.fieldCryptoHandshake = nil
	}
}

func (r *Readonly_RegisterData) GetBusId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldBusId
}

func (r *Readonly_RegisterData) GetPid() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldPid
}

func (r *Readonly_RegisterData) GetHostname() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldHostname
}

func (r *Readonly_RegisterData) GetChannels() []*Readonly_ChannelData {
	if r == nil {
		var zero []*Readonly_ChannelData
		return zero
	}
	return r.fieldChannels
}

func (r *Readonly_RegisterData) GetSupportedChannelSchema() []string {
	if r == nil {
		var zero []string
		return zero
	}
	return r.fieldSupportedChannelSchema
}

func (r *Readonly_RegisterData) GetSupportedCompressionAlgorithm() []ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if r == nil {
		var zero []ATBUS_COMPRESSION_ALGORITHM_TYPE
		return zero
	}
	return r.fieldSupportedCompressionAlgorithm
}

func (r *Readonly_RegisterData) GetFlags() uint32 {
	if r == nil {
		var zero uint32
		return zero
	}
	return r.fieldFlags
}

func (r *Readonly_RegisterData) GetAccessKey() *Readonly_AccessData {
	if r == nil {
		var zero *Readonly_AccessData
		return zero
	}
	return r.fieldAccessKey
}

func (r *Readonly_RegisterData) GetHashCode() string {
	if r == nil {
		var zero string
		return zero
	}
	return r.fieldHashCode
}

func (r *Readonly_RegisterData) GetCryptoHandshake() *Readonly_CryptoHandshakeData {
	if r == nil {
		var zero *Readonly_CryptoHandshakeData
		return zero
	}
	return r.fieldCryptoHandshake
}

// ===== Mutable methods for RegisterData ===== Repeated =====
func (m *RegisterData) MutableChannels() []*ChannelData {
	if m.Channels == nil {
		m.Channels = []*ChannelData{}
	}
	return m.Channels
}

// ===== ReverseIfNil methods for RegisterData ===== Repeated =====
func (m *RegisterData) ReverseIfNilChannels(l int) []*ChannelData {
	if m.Channels == nil {
		m.Channels = make([]*ChannelData, 0, l)
	}
	return m.Channels
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendChannels(d *ChannelData) {
	if m.Channels == nil {
		m.Channels = []*ChannelData{}
	}
	m.Channels = append(m.Channels, d)
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendAndReverseChannels(l int, d *ChannelData) {
	if m.Channels == nil {
		m.Channels = make([]*ChannelData, 0, l)
	}
	m.Channels = append(m.Channels, d)
}

// ===== Add methods for RegisterData ===== Repeated =====
func (m *RegisterData) AddChannels() *ChannelData {
	if m.Channels == nil {
		m.Channels = []*ChannelData{}
	}
	addValue := new(ChannelData)
	m.Channels = append(m.Channels, addValue)
	return addValue
}

// ===== Merge methods for RegisterData ===== Repeated =====
func (m *RegisterData) MergeChannels(d []*ChannelData) []*ChannelData {
	if m.Channels == nil {
		m.Channels = []*ChannelData{}
	}
	m.Channels = append(m.Channels, d...)
	return m.Channels
}

// ===== RemoveLast methods for RegisterData ===== Repeated =====
func (m *RegisterData) RemoveLastChannels() {
	if m.Channels == nil {
		m.Channels = []*ChannelData{}
	}
	if len(m.Channels) != 0 {
		m.Channels = m.Channels[:len(m.Channels)-1]
	}
}

// ===== Mutable methods for RegisterData ===== Repeated =====
func (m *RegisterData) MutableSupportedChannelSchema() []string {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = []string{}
	}
	return m.SupportedChannelSchema
}

// ===== ReverseIfNil methods for RegisterData ===== Repeated =====
func (m *RegisterData) ReverseIfNilSupportedChannelSchema(l int) []string {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = make([]string, 0, l)
	}
	return m.SupportedChannelSchema
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendSupportedChannelSchema(d string) {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = []string{}
	}
	m.SupportedChannelSchema = append(m.SupportedChannelSchema, d)
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendAndReverseSupportedChannelSchema(l int, d string) {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = make([]string, 0, l)
	}
	m.SupportedChannelSchema = append(m.SupportedChannelSchema, d)
}

// ===== Merge methods for RegisterData ===== Repeated =====
func (m *RegisterData) MergeSupportedChannelSchema(d []string) []string {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = []string{}
	}
	m.SupportedChannelSchema = append(m.SupportedChannelSchema, d...)
	return m.SupportedChannelSchema
}

// ===== RemoveLast methods for RegisterData ===== Repeated =====
func (m *RegisterData) RemoveLastSupportedChannelSchema() {
	if m.SupportedChannelSchema == nil {
		m.SupportedChannelSchema = []string{}
	}
	if len(m.SupportedChannelSchema) != 0 {
		m.SupportedChannelSchema = m.SupportedChannelSchema[:len(m.SupportedChannelSchema)-1]
	}
}

// ===== Mutable methods for RegisterData ===== Repeated =====
func (m *RegisterData) MutableSupportedCompressionAlgorithm() []ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = []ATBUS_COMPRESSION_ALGORITHM_TYPE{}
	}
	return m.SupportedCompressionAlgorithm
}

// ===== ReverseIfNil methods for RegisterData ===== Repeated =====
func (m *RegisterData) ReverseIfNilSupportedCompressionAlgorithm(l int) []ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = make([]ATBUS_COMPRESSION_ALGORITHM_TYPE, 0, l)
	}
	return m.SupportedCompressionAlgorithm
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendSupportedCompressionAlgorithm(d ATBUS_COMPRESSION_ALGORITHM_TYPE) {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = []ATBUS_COMPRESSION_ALGORITHM_TYPE{}
	}
	m.SupportedCompressionAlgorithm = append(m.SupportedCompressionAlgorithm, d)
}

// ===== Append methods for RegisterData ===== Repeated =====
func (m *RegisterData) AppendAndReverseSupportedCompressionAlgorithm(l int, d ATBUS_COMPRESSION_ALGORITHM_TYPE) {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = make([]ATBUS_COMPRESSION_ALGORITHM_TYPE, 0, l)
	}
	m.SupportedCompressionAlgorithm = append(m.SupportedCompressionAlgorithm, d)
}

// ===== Merge methods for RegisterData ===== Repeated =====
func (m *RegisterData) MergeSupportedCompressionAlgorithm(d []ATBUS_COMPRESSION_ALGORITHM_TYPE) []ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = []ATBUS_COMPRESSION_ALGORITHM_TYPE{}
	}
	m.SupportedCompressionAlgorithm = append(m.SupportedCompressionAlgorithm, d...)
	return m.SupportedCompressionAlgorithm
}

// ===== RemoveLast methods for RegisterData ===== Repeated =====
func (m *RegisterData) RemoveLastSupportedCompressionAlgorithm() {
	if m.SupportedCompressionAlgorithm == nil {
		m.SupportedCompressionAlgorithm = []ATBUS_COMPRESSION_ALGORITHM_TYPE{}
	}
	if len(m.SupportedCompressionAlgorithm) != 0 {
		m.SupportedCompressionAlgorithm = m.SupportedCompressionAlgorithm[:len(m.SupportedCompressionAlgorithm)-1]
	}
}

// ===== Mutable methods for RegisterData ===== Message =====
func (m *RegisterData) MutableAccessKey() *AccessData {
	if m.AccessKey == nil {
		m.AccessKey = new(AccessData)
	}
	return m.AccessKey
}

// ===== Mutable methods for RegisterData ===== Message =====
func (m *RegisterData) MutableCryptoHandshake() *CryptoHandshakeData {
	if m.CryptoHandshake == nil {
		m.CryptoHandshake = new(CryptoHandshakeData)
	}
	return m.CryptoHandshake
}

// ===== Clone methods for HandshakeConfirmData ===== Message ====
func (m *HandshakeConfirmData) Clone() *HandshakeConfirmData {
	if m == nil {
		return new(HandshakeConfirmData)
	}
	return proto.Clone(m).(*HandshakeConfirmData)
}

// ===== Merge methods for HandshakeConfirmData ===== Message ====
func (m *HandshakeConfirmData) Merge(src *HandshakeConfirmData) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for HandshakeConfirmData ===== Message ====
func (m *HandshakeConfirmData) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for HandshakeConfirmData ===== Message =====
func (_ *HandshakeConfirmData) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[HandshakeConfirmData]()
}

// ===== Readonly wrapper for HandshakeConfirmData ===== Message ====
type Readonly_HandshakeConfirmData struct {
	protoData     *HandshakeConfirmData
	fieldSequence uint64
}

func (r *Readonly_HandshakeConfirmData) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *HandshakeConfirmData) ToReadonly() *Readonly_HandshakeConfirmData {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_HandshakeConfirmData{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_HandshakeConfirmData) CloneMessage() *HandshakeConfirmData {
	if r == nil {
		return new(HandshakeConfirmData)
	}
	return r.protoData.Clone()
}

func (r *Readonly_HandshakeConfirmData) ToMessage() *HandshakeConfirmData {
	return r.CloneMessage()
}

func (r Readonly_HandshakeConfirmData) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_HandshakeConfirmData) initFromProto(src *HandshakeConfirmData) {
	if r == nil || src == nil {
		return
	}
	r.fieldSequence = src.GetSequence()
}

func (r *Readonly_HandshakeConfirmData) GetSequence() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldSequence
}

// ===== Clone methods for MessageHeadCrypto ===== Message ====
func (m *MessageHeadCrypto) Clone() *MessageHeadCrypto {
	if m == nil {
		return new(MessageHeadCrypto)
	}
	return proto.Clone(m).(*MessageHeadCrypto)
}

// ===== Merge methods for MessageHeadCrypto ===== Message ====
func (m *MessageHeadCrypto) Merge(src *MessageHeadCrypto) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for MessageHeadCrypto ===== Message ====
func (m *MessageHeadCrypto) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for MessageHeadCrypto ===== Message =====
func (_ *MessageHeadCrypto) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageHeadCrypto]()
}

// ===== Readonly wrapper for MessageHeadCrypto ===== Message ====
type Readonly_MessageHeadCrypto struct {
	protoData      *MessageHeadCrypto
	fieldAlgorithm ATBUS_CRYPTO_ALGORITHM_TYPE
	fieldIv        []byte
	fieldAad       []byte
}

func (r *Readonly_MessageHeadCrypto) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *MessageHeadCrypto) ToReadonly() *Readonly_MessageHeadCrypto {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_MessageHeadCrypto{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_MessageHeadCrypto) CloneMessage() *MessageHeadCrypto {
	if r == nil {
		return new(MessageHeadCrypto)
	}
	return r.protoData.Clone()
}

func (r *Readonly_MessageHeadCrypto) ToMessage() *MessageHeadCrypto {
	return r.CloneMessage()
}

func (r Readonly_MessageHeadCrypto) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_MessageHeadCrypto) initFromProto(src *MessageHeadCrypto) {
	if r == nil || src == nil {
		return
	}
	r.fieldAlgorithm = src.GetAlgorithm()
	if v := src.GetIv(); len(v) != 0 {
		r.fieldIv = append([]byte(nil), v...)
	} else {
		r.fieldIv = nil
	}
	if v := src.GetAad(); len(v) != 0 {
		r.fieldAad = append([]byte(nil), v...)
	} else {
		r.fieldAad = nil
	}
}

func (r *Readonly_MessageHeadCrypto) GetAlgorithm() ATBUS_CRYPTO_ALGORITHM_TYPE {
	if r == nil {
		var zero ATBUS_CRYPTO_ALGORITHM_TYPE
		return zero
	}
	return r.fieldAlgorithm
}

func (r *Readonly_MessageHeadCrypto) GetIv() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldIv) == 0 {
		return r.fieldIv
	}
	dup := make([]byte, len(r.fieldIv))
	copy(dup, r.fieldIv)
	return dup
}

func (r *Readonly_MessageHeadCrypto) GetAad() []byte {
	if r == nil {
		var zero []byte
		return zero
	}
	if len(r.fieldAad) == 0 {
		return r.fieldAad
	}
	dup := make([]byte, len(r.fieldAad))
	copy(dup, r.fieldAad)
	return dup
}

// ===== Clone methods for MessageHeadCompression ===== Message ====
func (m *MessageHeadCompression) Clone() *MessageHeadCompression {
	if m == nil {
		return new(MessageHeadCompression)
	}
	return proto.Clone(m).(*MessageHeadCompression)
}

// ===== Merge methods for MessageHeadCompression ===== Message ====
func (m *MessageHeadCompression) Merge(src *MessageHeadCompression) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for MessageHeadCompression ===== Message ====
func (m *MessageHeadCompression) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for MessageHeadCompression ===== Message =====
func (_ *MessageHeadCompression) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageHeadCompression]()
}

// ===== Readonly wrapper for MessageHeadCompression ===== Message ====
type Readonly_MessageHeadCompression struct {
	protoData         *MessageHeadCompression
	fieldType         ATBUS_COMPRESSION_ALGORITHM_TYPE
	fieldOriginalSize uint64
}

func (r *Readonly_MessageHeadCompression) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *MessageHeadCompression) ToReadonly() *Readonly_MessageHeadCompression {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_MessageHeadCompression{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_MessageHeadCompression) CloneMessage() *MessageHeadCompression {
	if r == nil {
		return new(MessageHeadCompression)
	}
	return r.protoData.Clone()
}

func (r *Readonly_MessageHeadCompression) ToMessage() *MessageHeadCompression {
	return r.CloneMessage()
}

func (r Readonly_MessageHeadCompression) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_MessageHeadCompression) initFromProto(src *MessageHeadCompression) {
	if r == nil || src == nil {
		return
	}
	r.fieldType = src.GetType()
	r.fieldOriginalSize = src.GetOriginalSize()
}

func (r *Readonly_MessageHeadCompression) GetType() ATBUS_COMPRESSION_ALGORITHM_TYPE {
	if r == nil {
		var zero ATBUS_COMPRESSION_ALGORITHM_TYPE
		return zero
	}
	return r.fieldType
}

func (r *Readonly_MessageHeadCompression) GetOriginalSize() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldOriginalSize
}

// ===== Clone methods for MessageHead ===== Message ====
func (m *MessageHead) Clone() *MessageHead {
	if m == nil {
		return new(MessageHead)
	}
	return proto.Clone(m).(*MessageHead)
}

// ===== Merge methods for MessageHead ===== Message ====
func (m *MessageHead) Merge(src *MessageHead) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for MessageHead ===== Message ====
func (m *MessageHead) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for MessageHead ===== Message =====
func (_ *MessageHead) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageHead]()
}

// ===== Readonly wrapper for MessageHead ===== Message ====
type Readonly_MessageHead struct {
	protoData        *MessageHead
	fieldVersion     int32
	fieldType        int32
	fieldResultCode  int32
	fieldSequence    uint64
	fieldSourceBusId uint64
	fieldCrypto      *Readonly_MessageHeadCrypto
	fieldCompression *Readonly_MessageHeadCompression
	fieldBodySize    uint64
}

func (r *Readonly_MessageHead) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *MessageHead) ToReadonly() *Readonly_MessageHead {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_MessageHead{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_MessageHead) CloneMessage() *MessageHead {
	if r == nil {
		return new(MessageHead)
	}
	return r.protoData.Clone()
}

func (r *Readonly_MessageHead) ToMessage() *MessageHead {
	return r.CloneMessage()
}

func (r Readonly_MessageHead) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_MessageHead) initFromProto(src *MessageHead) {
	if r == nil || src == nil {
		return
	}
	r.fieldVersion = src.GetVersion()
	r.fieldType = src.GetType()
	r.fieldResultCode = src.GetResultCode()
	r.fieldSequence = src.GetSequence()
	r.fieldSourceBusId = src.GetSourceBusId()
	if v := src.GetCrypto(); v != nil {
		r.fieldCrypto = v.ToReadonly()
	} else {
		r.fieldCrypto = nil
	}
	if v := src.GetCompression(); v != nil {
		r.fieldCompression = v.ToReadonly()
	} else {
		r.fieldCompression = nil
	}
	r.fieldBodySize = src.GetBodySize()
}

func (r *Readonly_MessageHead) GetVersion() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldVersion
}

func (r *Readonly_MessageHead) GetType() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldType
}

func (r *Readonly_MessageHead) GetResultCode() int32 {
	if r == nil {
		var zero int32
		return zero
	}
	return r.fieldResultCode
}

func (r *Readonly_MessageHead) GetSequence() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldSequence
}

func (r *Readonly_MessageHead) GetSourceBusId() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldSourceBusId
}

func (r *Readonly_MessageHead) GetCrypto() *Readonly_MessageHeadCrypto {
	if r == nil {
		var zero *Readonly_MessageHeadCrypto
		return zero
	}
	return r.fieldCrypto
}

func (r *Readonly_MessageHead) GetCompression() *Readonly_MessageHeadCompression {
	if r == nil {
		var zero *Readonly_MessageHeadCompression
		return zero
	}
	return r.fieldCompression
}

func (r *Readonly_MessageHead) GetBodySize() uint64 {
	if r == nil {
		var zero uint64
		return zero
	}
	return r.fieldBodySize
}

// ===== Mutable methods for MessageHead ===== Message =====
func (m *MessageHead) MutableCrypto() *MessageHeadCrypto {
	if m.Crypto == nil {
		m.Crypto = new(MessageHeadCrypto)
	}
	return m.Crypto
}

// ===== Mutable methods for MessageHead ===== Message =====
func (m *MessageHead) MutableCompression() *MessageHeadCompression {
	if m.Compression == nil {
		m.Compression = new(MessageHeadCompression)
	}
	return m.Compression
}

// ===== Clone methods for MessageBody ===== Message ====
func (m *MessageBody) Clone() *MessageBody {
	if m == nil {
		return new(MessageBody)
	}
	return proto.Clone(m).(*MessageBody)
}

// ===== Merge methods for MessageBody ===== Message ====
func (m *MessageBody) Merge(src *MessageBody) {
	if m == nil {
		return
	}
	proto.Merge(m, src)
}

// ===== SlogValue methods for MessageBody ===== Message ====
func (m *MessageBody) LogValue() slog.Value {
	return slog.StringValue(pu.MessageReadableTextIndent(m))
}

// ===== GetMessageReflectType methods for MessageBody ===== Message =====
func (_ *MessageBody) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody]()
}

// ===== Readonly wrapper for MessageBody ===== Message ====
type Readonly_MessageBody struct {
	protoData        *MessageBody
	fieldMessageType getReadonlyMessageBody_MessageType
}

func (r *Readonly_MessageBody) ReadonlyProtoReflect() innerFile_libatbus_protocol_protoReadonlyMessage {
	if r == nil || r.protoData == nil {
		return nil
	}
	return r.protoData.ProtoReflect()
}

func (m *MessageBody) ToReadonly() *Readonly_MessageBody {
	if m == nil {
		return nil
	}
	clone := m.Clone()
	ro := &Readonly_MessageBody{protoData: clone}
	ro.initFromProto(clone)
	return ro
}

func (r *Readonly_MessageBody) CloneMessage() *MessageBody {
	if r == nil {
		return new(MessageBody)
	}
	return r.protoData.Clone()
}

func (r *Readonly_MessageBody) ToMessage() *MessageBody {
	return r.CloneMessage()
}

func (r Readonly_MessageBody) LogValue() slog.Value {
	return r.protoData.LogValue()
}

func (r *Readonly_MessageBody) initFromProto(src *MessageBody) {
	if r == nil || src == nil {
		return
	}
	switch v := src.MessageType.(type) {
	case *MessageBody_CustomCommandReq:
		var inner *Readonly_CustomCommandData
		if nested := v.CustomCommandReq; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_CustomCommandReq{value: inner}
	case *MessageBody_CustomCommandRsp:
		var inner *Readonly_CustomCommandData
		if nested := v.CustomCommandRsp; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_CustomCommandRsp{value: inner}
	case *MessageBody_DataTransformReq:
		var inner *Readonly_ForwardData
		if nested := v.DataTransformReq; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_DataTransformReq{value: inner}
	case *MessageBody_DataTransformRsp:
		var inner *Readonly_ForwardData
		if nested := v.DataTransformRsp; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_DataTransformRsp{value: inner}
	case *MessageBody_NodeRegisterReq:
		var inner *Readonly_RegisterData
		if nested := v.NodeRegisterReq; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_NodeRegisterReq{value: inner}
	case *MessageBody_NodeRegisterRsp:
		var inner *Readonly_RegisterData
		if nested := v.NodeRegisterRsp; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_NodeRegisterRsp{value: inner}
	case *MessageBody_NodePingReq:
		var inner *Readonly_PingData
		if nested := v.NodePingReq; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_NodePingReq{value: inner}
	case *MessageBody_NodePongRsp:
		var inner *Readonly_PingData
		if nested := v.NodePongRsp; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_NodePongRsp{value: inner}
	case *MessageBody_HandshakeConfirm:
		var inner *Readonly_HandshakeConfirmData
		if nested := v.HandshakeConfirm; nested != nil {
			inner = nested.ToReadonly()
		}
		r.fieldMessageType = &Readonly_MessageBody_HandshakeConfirm{value: inner}
	default:
		r.fieldMessageType = nil
	}
}

func (r *Readonly_MessageBody) GetCustomCommandReq() *Readonly_CustomCommandData {
	if r == nil {
		var zero *Readonly_CustomCommandData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_CustomCommandReq); ok && x != nil {
		return x.GetCustomCommandReq()
	}
	var zero *Readonly_CustomCommandData
	return zero
}

func (r *Readonly_MessageBody) GetCustomCommandRsp() *Readonly_CustomCommandData {
	if r == nil {
		var zero *Readonly_CustomCommandData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_CustomCommandRsp); ok && x != nil {
		return x.GetCustomCommandRsp()
	}
	var zero *Readonly_CustomCommandData
	return zero
}

func (r *Readonly_MessageBody) GetDataTransformReq() *Readonly_ForwardData {
	if r == nil {
		var zero *Readonly_ForwardData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_DataTransformReq); ok && x != nil {
		return x.GetDataTransformReq()
	}
	var zero *Readonly_ForwardData
	return zero
}

func (r *Readonly_MessageBody) GetDataTransformRsp() *Readonly_ForwardData {
	if r == nil {
		var zero *Readonly_ForwardData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_DataTransformRsp); ok && x != nil {
		return x.GetDataTransformRsp()
	}
	var zero *Readonly_ForwardData
	return zero
}

func (r *Readonly_MessageBody) GetNodeRegisterReq() *Readonly_RegisterData {
	if r == nil {
		var zero *Readonly_RegisterData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_NodeRegisterReq); ok && x != nil {
		return x.GetNodeRegisterReq()
	}
	var zero *Readonly_RegisterData
	return zero
}

func (r *Readonly_MessageBody) GetNodeRegisterRsp() *Readonly_RegisterData {
	if r == nil {
		var zero *Readonly_RegisterData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_NodeRegisterRsp); ok && x != nil {
		return x.GetNodeRegisterRsp()
	}
	var zero *Readonly_RegisterData
	return zero
}

func (r *Readonly_MessageBody) GetNodePingReq() *Readonly_PingData {
	if r == nil {
		var zero *Readonly_PingData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_NodePingReq); ok && x != nil {
		return x.GetNodePingReq()
	}
	var zero *Readonly_PingData
	return zero
}

func (r *Readonly_MessageBody) GetNodePongRsp() *Readonly_PingData {
	if r == nil {
		var zero *Readonly_PingData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_NodePongRsp); ok && x != nil {
		return x.GetNodePongRsp()
	}
	var zero *Readonly_PingData
	return zero
}

func (r *Readonly_MessageBody) GetHandshakeConfirm() *Readonly_HandshakeConfirmData {
	if r == nil {
		var zero *Readonly_HandshakeConfirmData
		return zero
	}
	if x, ok := r.fieldMessageType.(*Readonly_MessageBody_HandshakeConfirm); ok && x != nil {
		return x.GetHandshakeConfirm()
	}
	var zero *Readonly_HandshakeConfirmData
	return zero
}

func (r *Readonly_MessageBody) GetMessageTypeOneofCase() MessageBody_EnMessageTypeID {
	if r == nil {
		return 0
	}
	if r.fieldMessageType == nil {
		return MessageBody_EnMessageTypeID_NONE
	}
	return r.fieldMessageType.GetMessageBody_MessageType()
}

func (r *Readonly_MessageBody) GetMessageTypeTypeID() lu.TypeID {
	if r == nil {
		return 0
	}
	if r.fieldMessageType == nil {
		return 0
	}
	return r.fieldMessageType.GetTypeIDMessageBody_MessageType()
}

// ===== Readonly interface for MessageBody Oneof MessageType ===== Oneof ====
type getReadonlyMessageBody_MessageType interface {
	GetMessageBody_MessageType() MessageBody_EnMessageTypeID
	GetTypeIDMessageBody_MessageType() lu.TypeID
}

// ===== Readonly struct for MessageBody_CustomCommandReq ===== Oneof option ====
type Readonly_MessageBody_CustomCommandReq struct {
	value *Readonly_CustomCommandData
}

func (r *Readonly_MessageBody_CustomCommandReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_CustomCommandReq
}

func (r *Readonly_MessageBody_CustomCommandReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_CustomCommandReq()
}

func (r *Readonly_MessageBody_CustomCommandReq) GetCustomCommandReq() *Readonly_CustomCommandData {
	if r == nil {
		var zero *Readonly_CustomCommandData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_CustomCommandRsp ===== Oneof option ====
type Readonly_MessageBody_CustomCommandRsp struct {
	value *Readonly_CustomCommandData
}

func (r *Readonly_MessageBody_CustomCommandRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_CustomCommandRsp
}

func (r *Readonly_MessageBody_CustomCommandRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_CustomCommandRsp()
}

func (r *Readonly_MessageBody_CustomCommandRsp) GetCustomCommandRsp() *Readonly_CustomCommandData {
	if r == nil {
		var zero *Readonly_CustomCommandData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_DataTransformReq ===== Oneof option ====
type Readonly_MessageBody_DataTransformReq struct {
	value *Readonly_ForwardData
}

func (r *Readonly_MessageBody_DataTransformReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_DataTransformReq
}

func (r *Readonly_MessageBody_DataTransformReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_DataTransformReq()
}

func (r *Readonly_MessageBody_DataTransformReq) GetDataTransformReq() *Readonly_ForwardData {
	if r == nil {
		var zero *Readonly_ForwardData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_DataTransformRsp ===== Oneof option ====
type Readonly_MessageBody_DataTransformRsp struct {
	value *Readonly_ForwardData
}

func (r *Readonly_MessageBody_DataTransformRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_DataTransformRsp
}

func (r *Readonly_MessageBody_DataTransformRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_DataTransformRsp()
}

func (r *Readonly_MessageBody_DataTransformRsp) GetDataTransformRsp() *Readonly_ForwardData {
	if r == nil {
		var zero *Readonly_ForwardData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_NodeRegisterReq ===== Oneof option ====
type Readonly_MessageBody_NodeRegisterReq struct {
	value *Readonly_RegisterData
}

func (r *Readonly_MessageBody_NodeRegisterReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodeRegisterReq
}

func (r *Readonly_MessageBody_NodeRegisterReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_NodeRegisterReq()
}

func (r *Readonly_MessageBody_NodeRegisterReq) GetNodeRegisterReq() *Readonly_RegisterData {
	if r == nil {
		var zero *Readonly_RegisterData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_NodeRegisterRsp ===== Oneof option ====
type Readonly_MessageBody_NodeRegisterRsp struct {
	value *Readonly_RegisterData
}

func (r *Readonly_MessageBody_NodeRegisterRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodeRegisterRsp
}

func (r *Readonly_MessageBody_NodeRegisterRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_NodeRegisterRsp()
}

func (r *Readonly_MessageBody_NodeRegisterRsp) GetNodeRegisterRsp() *Readonly_RegisterData {
	if r == nil {
		var zero *Readonly_RegisterData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_NodePingReq ===== Oneof option ====
type Readonly_MessageBody_NodePingReq struct {
	value *Readonly_PingData
}

func (r *Readonly_MessageBody_NodePingReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodePingReq
}

func (r *Readonly_MessageBody_NodePingReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_NodePingReq()
}

func (r *Readonly_MessageBody_NodePingReq) GetNodePingReq() *Readonly_PingData {
	if r == nil {
		var zero *Readonly_PingData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_NodePongRsp ===== Oneof option ====
type Readonly_MessageBody_NodePongRsp struct {
	value *Readonly_PingData
}

func (r *Readonly_MessageBody_NodePongRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodePongRsp
}

func (r *Readonly_MessageBody_NodePongRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_NodePongRsp()
}

func (r *Readonly_MessageBody_NodePongRsp) GetNodePongRsp() *Readonly_PingData {
	if r == nil {
		var zero *Readonly_PingData
		return zero
	}
	return r.value
}

// ===== Readonly struct for MessageBody_HandshakeConfirm ===== Oneof option ====
type Readonly_MessageBody_HandshakeConfirm struct {
	value *Readonly_HandshakeConfirmData
}

func (r *Readonly_MessageBody_HandshakeConfirm) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_HandshakeConfirm
}

func (r *Readonly_MessageBody_HandshakeConfirm) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return GetTypeIDMessageBody_HandshakeConfirm()
}

func (r *Readonly_MessageBody_HandshakeConfirm) GetHandshakeConfirm() *Readonly_HandshakeConfirmData {
	if r == nil {
		var zero *Readonly_HandshakeConfirmData
		return zero
	}
	return r.value
}

// ===== Case Enum for MessageBody Oneof MessageType ===== Oneof =====
type MessageBody_EnMessageTypeID int32

const (
	MessageBody_EnMessageTypeID_NONE             MessageBody_EnMessageTypeID = 0 // none
	MessageBody_EnMessageTypeID_CustomCommandReq MessageBody_EnMessageTypeID = 1 // custom_command_req
	MessageBody_EnMessageTypeID_CustomCommandRsp MessageBody_EnMessageTypeID = 2 // custom_command_rsp
	MessageBody_EnMessageTypeID_DataTransformReq MessageBody_EnMessageTypeID = 3 // data_transform_req
	MessageBody_EnMessageTypeID_DataTransformRsp MessageBody_EnMessageTypeID = 4 // data_transform_rsp
	MessageBody_EnMessageTypeID_NodeRegisterReq  MessageBody_EnMessageTypeID = 5 // node_register_req
	MessageBody_EnMessageTypeID_NodeRegisterRsp  MessageBody_EnMessageTypeID = 6 // node_register_rsp
	MessageBody_EnMessageTypeID_NodePingReq      MessageBody_EnMessageTypeID = 7 // node_ping_req
	MessageBody_EnMessageTypeID_NodePongRsp      MessageBody_EnMessageTypeID = 8 // node_pong_rsp
	MessageBody_EnMessageTypeID_HandshakeConfirm MessageBody_EnMessageTypeID = 9 // handshake_confirm
)

// ===== GetCase interface for MessageBody Oneof MessageType ===== Oneof =====
type getMessageBody_MessageType interface {
	GetMessageBody_MessageType() MessageBody_EnMessageTypeID
	GetTypeIDMessageBody_MessageType() lu.TypeID
	GetFieldNameMessageBody_MessageType() string
}

// ===== GetCase methods for MessageBody Oneof MessageType ===== Oneof =====
func (m *MessageBody) GetMessageTypeOneofCase() MessageBody_EnMessageTypeID {
	if m == nil {
		return 0
	}
	v, ok := m.MessageType.(getMessageBody_MessageType)
	if !ok {
		return 0
	}
	return v.GetMessageBody_MessageType()
}

func (m *MessageBody) GetMessageTypeOneofName() string {
	if m == nil {
		return ""
	}
	v, ok := m.MessageType.(getMessageBody_MessageType)
	if !ok {
		return ""
	}
	return v.GetFieldNameMessageBody_MessageType()
}

// ===== GetOneofTypeID methods for MessageBody Oneof MessageType ===== Oneof =====
func (m *MessageBody) GetMessageTypeTypeID() lu.TypeID {
	if m == nil {
		return 0
	}
	v, ok := m.MessageType.(getMessageBody_MessageType)
	if !ok {
		return 0
	}
	return v.GetTypeIDMessageBody_MessageType()
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableCustomCommandReq() *CustomCommandData {
	if x, ok := m.MessageType.(*MessageBody_CustomCommandReq); ok {
		return x.MutableCustomCommandReq()
	}
	x := new(MessageBody_CustomCommandReq)
	m.MessageType = x
	return x.MutableCustomCommandReq()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_CustomCommandReq() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandReq]()
}
func (_ *MessageBody_CustomCommandReq) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandReq]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_CustomCommandReq ===== Oneof =====
func (m *MessageBody_CustomCommandReq) MutableCustomCommandReq() *CustomCommandData {
	if m.CustomCommandReq == nil {
		m.CustomCommandReq = new(CustomCommandData)
	}
	return m.CustomCommandReq
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_CustomCommandReq ===== Oneof =====
func (m *MessageBody_CustomCommandReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_CustomCommandReq
}
func (m *MessageBody_CustomCommandReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandReq]()
}
func (m *MessageBody_CustomCommandReq) GetFieldNameMessageBody_MessageType() string {
	return "custom_command_req"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableCustomCommandRsp() *CustomCommandData {
	if x, ok := m.MessageType.(*MessageBody_CustomCommandRsp); ok {
		return x.MutableCustomCommandRsp()
	}
	x := new(MessageBody_CustomCommandRsp)
	m.MessageType = x
	return x.MutableCustomCommandRsp()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_CustomCommandRsp() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandRsp]()
}
func (_ *MessageBody_CustomCommandRsp) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandRsp]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_CustomCommandRsp ===== Oneof =====
func (m *MessageBody_CustomCommandRsp) MutableCustomCommandRsp() *CustomCommandData {
	if m.CustomCommandRsp == nil {
		m.CustomCommandRsp = new(CustomCommandData)
	}
	return m.CustomCommandRsp
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_CustomCommandRsp ===== Oneof =====
func (m *MessageBody_CustomCommandRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_CustomCommandRsp
}
func (m *MessageBody_CustomCommandRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_CustomCommandRsp]()
}
func (m *MessageBody_CustomCommandRsp) GetFieldNameMessageBody_MessageType() string {
	return "custom_command_rsp"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableDataTransformReq() *ForwardData {
	if x, ok := m.MessageType.(*MessageBody_DataTransformReq); ok {
		return x.MutableDataTransformReq()
	}
	x := new(MessageBody_DataTransformReq)
	m.MessageType = x
	return x.MutableDataTransformReq()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_DataTransformReq() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformReq]()
}
func (_ *MessageBody_DataTransformReq) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformReq]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_DataTransformReq ===== Oneof =====
func (m *MessageBody_DataTransformReq) MutableDataTransformReq() *ForwardData {
	if m.DataTransformReq == nil {
		m.DataTransformReq = new(ForwardData)
	}
	return m.DataTransformReq
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_DataTransformReq ===== Oneof =====
func (m *MessageBody_DataTransformReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_DataTransformReq
}
func (m *MessageBody_DataTransformReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformReq]()
}
func (m *MessageBody_DataTransformReq) GetFieldNameMessageBody_MessageType() string {
	return "data_transform_req"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableDataTransformRsp() *ForwardData {
	if x, ok := m.MessageType.(*MessageBody_DataTransformRsp); ok {
		return x.MutableDataTransformRsp()
	}
	x := new(MessageBody_DataTransformRsp)
	m.MessageType = x
	return x.MutableDataTransformRsp()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_DataTransformRsp() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformRsp]()
}
func (_ *MessageBody_DataTransformRsp) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformRsp]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_DataTransformRsp ===== Oneof =====
func (m *MessageBody_DataTransformRsp) MutableDataTransformRsp() *ForwardData {
	if m.DataTransformRsp == nil {
		m.DataTransformRsp = new(ForwardData)
	}
	return m.DataTransformRsp
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_DataTransformRsp ===== Oneof =====
func (m *MessageBody_DataTransformRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_DataTransformRsp
}
func (m *MessageBody_DataTransformRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_DataTransformRsp]()
}
func (m *MessageBody_DataTransformRsp) GetFieldNameMessageBody_MessageType() string {
	return "data_transform_rsp"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableNodeRegisterReq() *RegisterData {
	if x, ok := m.MessageType.(*MessageBody_NodeRegisterReq); ok {
		return x.MutableNodeRegisterReq()
	}
	x := new(MessageBody_NodeRegisterReq)
	m.MessageType = x
	return x.MutableNodeRegisterReq()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_NodeRegisterReq() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterReq]()
}
func (_ *MessageBody_NodeRegisterReq) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterReq]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_NodeRegisterReq ===== Oneof =====
func (m *MessageBody_NodeRegisterReq) MutableNodeRegisterReq() *RegisterData {
	if m.NodeRegisterReq == nil {
		m.NodeRegisterReq = new(RegisterData)
	}
	return m.NodeRegisterReq
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_NodeRegisterReq ===== Oneof =====
func (m *MessageBody_NodeRegisterReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodeRegisterReq
}
func (m *MessageBody_NodeRegisterReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterReq]()
}
func (m *MessageBody_NodeRegisterReq) GetFieldNameMessageBody_MessageType() string {
	return "node_register_req"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableNodeRegisterRsp() *RegisterData {
	if x, ok := m.MessageType.(*MessageBody_NodeRegisterRsp); ok {
		return x.MutableNodeRegisterRsp()
	}
	x := new(MessageBody_NodeRegisterRsp)
	m.MessageType = x
	return x.MutableNodeRegisterRsp()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_NodeRegisterRsp() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterRsp]()
}
func (_ *MessageBody_NodeRegisterRsp) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterRsp]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_NodeRegisterRsp ===== Oneof =====
func (m *MessageBody_NodeRegisterRsp) MutableNodeRegisterRsp() *RegisterData {
	if m.NodeRegisterRsp == nil {
		m.NodeRegisterRsp = new(RegisterData)
	}
	return m.NodeRegisterRsp
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_NodeRegisterRsp ===== Oneof =====
func (m *MessageBody_NodeRegisterRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodeRegisterRsp
}
func (m *MessageBody_NodeRegisterRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodeRegisterRsp]()
}
func (m *MessageBody_NodeRegisterRsp) GetFieldNameMessageBody_MessageType() string {
	return "node_register_rsp"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableNodePingReq() *PingData {
	if x, ok := m.MessageType.(*MessageBody_NodePingReq); ok {
		return x.MutableNodePingReq()
	}
	x := new(MessageBody_NodePingReq)
	m.MessageType = x
	return x.MutableNodePingReq()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_NodePingReq() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePingReq]()
}
func (_ *MessageBody_NodePingReq) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePingReq]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_NodePingReq ===== Oneof =====
func (m *MessageBody_NodePingReq) MutableNodePingReq() *PingData {
	if m.NodePingReq == nil {
		m.NodePingReq = new(PingData)
	}
	return m.NodePingReq
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_NodePingReq ===== Oneof =====
func (m *MessageBody_NodePingReq) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodePingReq
}
func (m *MessageBody_NodePingReq) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePingReq]()
}
func (m *MessageBody_NodePingReq) GetFieldNameMessageBody_MessageType() string {
	return "node_ping_req"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableNodePongRsp() *PingData {
	if x, ok := m.MessageType.(*MessageBody_NodePongRsp); ok {
		return x.MutableNodePongRsp()
	}
	x := new(MessageBody_NodePongRsp)
	m.MessageType = x
	return x.MutableNodePongRsp()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_NodePongRsp() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePongRsp]()
}
func (_ *MessageBody_NodePongRsp) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePongRsp]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_NodePongRsp ===== Oneof =====
func (m *MessageBody_NodePongRsp) MutableNodePongRsp() *PingData {
	if m.NodePongRsp == nil {
		m.NodePongRsp = new(PingData)
	}
	return m.NodePongRsp
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_NodePongRsp ===== Oneof =====
func (m *MessageBody_NodePongRsp) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_NodePongRsp
}
func (m *MessageBody_NodePongRsp) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_NodePongRsp]()
}
func (m *MessageBody_NodePongRsp) GetFieldNameMessageBody_MessageType() string {
	return "node_pong_rsp"
}

// ===== Mutable methods for MessageBody ===== Oneof =====
func (m *MessageBody) MutableHandshakeConfirm() *HandshakeConfirmData {
	if x, ok := m.MessageType.(*MessageBody_HandshakeConfirm); ok {
		return x.MutableHandshakeConfirm()
	}
	x := new(MessageBody_HandshakeConfirm)
	m.MessageType = x
	return x.MutableHandshakeConfirm()
}

// ===== Get reflect Type for MessageBody Oneof MessageType ===== Oneof =====
func GetTypeIDMessageBody_HandshakeConfirm() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_HandshakeConfirm]()
}
func (_ *MessageBody_HandshakeConfirm) GetTypeID() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_HandshakeConfirm]()
}

// ===== Mutable Message method for MessageBody Oneof MessageBody_HandshakeConfirm ===== Oneof =====
func (m *MessageBody_HandshakeConfirm) MutableHandshakeConfirm() *HandshakeConfirmData {
	if m.HandshakeConfirm == nil {
		m.HandshakeConfirm = new(HandshakeConfirmData)
	}
	return m.HandshakeConfirm
}

// ===== Oneof Interface for MessageBody Oneof MessageBody_HandshakeConfirm ===== Oneof =====
func (m *MessageBody_HandshakeConfirm) GetMessageBody_MessageType() MessageBody_EnMessageTypeID {
	return MessageBody_EnMessageTypeID_HandshakeConfirm
}
func (m *MessageBody_HandshakeConfirm) GetTypeIDMessageBody_MessageType() lu.TypeID {
	return lu.GetTypeIDOf[MessageBody_HandshakeConfirm]()
}
func (m *MessageBody_HandshakeConfirm) GetFieldNameMessageBody_MessageType() string {
	return "handshake_confirm"
}
